import React, { createContext, useState, useContext, useEffect } from 'react';

/**
 * ============================================================
 * ETHIOPIAN RESTAURANT POS SYSTEM - LANGUAGE CONTEXT
 * ============================================================
 * 
 * This file contains ALL translations for the entire POS system.
 * 
 * Supported languages:
 *   - English (en) - Default
 *   - Amharic (am) - አማርኛ
 * 
 * HOW TO USE IN COMPONENTS:
 * ============================================================
 * 
 * 1. Import the hook:
 *    import { useLanguage } from '../context/LanguageContext';
 * 
 * 2. Destructure what you need:
 *    const { t, language, setLanguage } = useLanguage();
 * 
 * 3. Use translations:
 *    <h1>{t('dashboard')}</h1>
 *    <button onClick={() => setLanguage('am')}>አማርኛ</button>
 * 
 * 4. To add a new language:
 *    - Add new object inside translations{}
 *    - Copy all keys from 'en' object
 *    - Translate values to your language
 * 
 * ============================================================
 */

// ============================================================
// TRANSLATIONS OBJECT
// ============================================================
const translations = {
  
  // ==========================================================
  // ENGLISH TRANSLATIONS (Default)
  // ==========================================================
  en: {
    // ---------- COMMON UI ----------
    dashboard: 'Dashboard',
    logout: 'Logout',
    welcome: 'Welcome back',
    readyToServe: 'Ready to serve customers',
    search: 'Search...',
    notifications: 'Notifications',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    refresh: 'Refresh',
    approve: 'Approve',
    reject: 'Reject',
    back: 'Back',
    confirm: 'Confirm',
    loading: 'Loading...',
    noData: 'No data available',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    total: 'Total',
    amount: 'Amount',
    description: 'Description',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    role: 'Role',
    loggedInAs: 'Logged in as',
    submit: 'Submit',
    update: 'Update',
    create: 'Create',
    close: 'Close',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',

    // ---------- USER ROLES ----------
    owner: 'Owner',
    manager: 'Manager',
    cashier: 'Cashier',
    waiter: 'Waiter',
    kitchen: 'Kitchen',
    admin: 'Admin',
    staff: 'Staff',

    // ---------- POS / CASHIER MODULE ----------
    posTerminal: 'POS Terminal',
    currentOrder: 'Current Order',
    cartEmpty: 'Cart is empty',
    checkout: 'Checkout',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    tax: 'Tax',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    mobile: 'Mobile',
    completeOrder: 'Complete Order',
    processPayment: 'Process Payment',
    customerName: 'Customer name',
    customerPhone: 'Customer phone',
    addToCart: 'Add to Cart',
    quantity: 'Quantity',
    items: 'Items',
    salesHistory: 'Sales History',
    readyForPayment: 'Ready for Payment',
    addToOrder: '+ Add to order',
    tapToAdd: 'Tap on menu items to add',
    manualOrder: 'Manual Order',
    walkInCustomer: 'Walk-in Customer',

    // ---------- KITCHEN MODULE ----------
    kitchenDashboard: 'Kitchen Dashboard',
    manageFoodPreparation: 'Manage food preparation',
    pending: 'Pending',
    preparing: 'Preparing',
    ready: 'Ready',
    completed: 'Completed',
    cancelled: 'Cancelled',
    startCooking: 'Start Cooking',
    markReady: 'Mark Ready',
    readyForPickup: 'Ready for Pickup',
    newOrderReceived: 'New order received',
    cooking: 'Cooking',
    ordersToPrepare: 'Orders to prepare',
    active: 'Active',

    // ---------- WAITER / TABLE MANAGEMENT ----------
    tableManagement: 'Table Management',
    selectTable: 'Select a table to start an order',
    floorPlan: 'Restaurant Floor Plan',
    available: 'Available',
    occupied: 'Occupied',
    reserved: 'Reserved',
    cleaning: 'Cleaning',
    capacity: 'Cap',
    table: 'Table',
    orderForTable: 'Order for Table',
    specialInstructions: 'Special instructions',
    sendToKitchen: 'Send to Kitchen',
    activeOrders: 'Active Orders',
    yourActiveOrders: 'Your Active Orders',
    orderNumber: 'Order Number',
    cancelOrder: 'Cancel Order',
    addMoreItems: 'Add More Items',
    addItems: 'Add Items',
    activeOrdersHidden: 'Hidden Orders',
    showOrders: 'Show Orders',
    noActiveOrdersMessage: 'No active orders',
    myOrders: 'My Orders',
    manageTables: 'Manage your restaurant tables and orders',
    hide: 'Hide',
    clickToCreateOrder: 'Click to create order',
    clickToAddItems: 'Click to add items',
    newOrderForTable: 'New Order for Table',
    seats: 'seats',
    searchMenu: 'Search menu...',
    allItems: 'All Items',
    sending: 'Sending...',
    itemsToAdd: 'Items to Add',
    noItemsSelected: 'No items selected',
    adding: 'Adding...',
    isReserved: 'is reserved',
    isCleaning: 'is being cleaned',
    orderSent: 'Order sent to kitchen',
    failedToSubmitOrder: 'Failed to submit order',
    orderCancelledSuccess: 'Order cancelled successfully!',
    failedToCancelOrder: 'Failed to cancel order',
    pendingConfirmations: 'Confirm Orders',
    tableStatus: 'Table Status',
    manageTableAvailability: 'Manage table availability, reservations, and cleaning status',
    changeStatus: 'Change Status',
    yourAssignedTables: 'Your Assigned Tables',
    noTablesAssigned: 'No Tables Assigned',
    contactManager: 'Please contact your manager',
    todaysShift: 'Today\'s Shift',
    toConfirm: 'To Confirm',
    awaitingConfirmation: 'Awaiting Confirmation',

    // ---------- QR CODE ORDERING ----------
    qrCodeAvailable: 'QR Code available',
    getQRCode: 'Get QR Code',
    qrCodeForTable: 'QR Code for Table',
    customersScanToOrder: 'Customers scan to view menu and order',
    qrCodeInstructions: 'Share this link with customers. They can scan the QR code to view the menu and place orders from their phone.',
    qrUrl: 'QR URL',
    copyQrUrl: 'Copy QR URL',
    qrNote: 'You can generate a physical QR code using any QR code generator website by pasting this URL.',
    printQRCodes: 'Print QR Codes',
    generateAndPrintQRCodes: 'Generate and print QR codes for all tables',
    printAll: 'Print All',
    copyUrl: 'Copy URL',
    qrPrintInstructions: 'Print this page and cut out each QR code. Place them on corresponding tables.',
    howQrWorks: 'How QR Ordering Works',
    step1: 'Scan QR code at your table',
    step2: 'Browse menu and add items',
    step3: 'Enter your details',
    step4: 'Place order - waiter confirms',

    // ---------- INVENTORY MANAGEMENT ----------
    inventoryManagement: 'Inventory Management',
    manageProductsAndIngredients: 'Manage products and ingredients',
    ingredients: 'Ingredients',
    products: 'Products',
    addIngredient: 'Add Ingredient',
    addProduct: 'Add Product',
    stock: 'Stock',
    minStock: 'Min Stock',
    unit: 'Unit',
    unitCost: 'Unit Cost',
    category: 'Category',
    supplier: 'Supplier',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    adjustStock: 'Adjust Stock',
    currentStock: 'Current Stock',
    lowStockDescription: 'The following ingredients are below minimum stock level:',
    left: 'left',
    min: 'Min',
    moreItems: 'more items',
    noIngredientsFound: 'No ingredients found',
    noProductsFound: 'No products found',
    deleteFailed: 'Failed to delete',
    ingredientsBelowMinStock: 'ingredients are below minimum stock level',
    addNew: 'Add New',
    selectUnit: 'Select unit',
    kilogram: 'Kilogram (kg)',
    gram: 'Gram (g)',
    liter: 'Liter (L)',
    milliliter: 'Milliliter (ml)',
    pieces: 'Pieces (pcs)',
    egVegetables: 'e.g., Vegetables',

    // ---------- WASTAGE TRACKING ----------
    wastageTracking: 'Wastage Tracking',
    trackIngredientWaste: 'Track ingredient waste from trimming, spoilage, and cooking loss',
    wastagePercentage: 'Wastage Factor (%)',
    cookingLoss: 'Cooking Loss (%)',
    yieldPercentage: 'Yield Percentage (%)',
    expectedUsage: 'Expected Usage',
    actualUsage: 'Actual Usage',
    wastageAmount: 'Wastage Amount',
    wastageCost: 'Wastage Cost',
    totalWastageCost: 'Total Wastage Cost',
    wastageReport: 'Wastage Report',
    wastageByIngredient: 'Wastage by Ingredient',
    dailyWastage: 'Daily Wastage',
    wastageDescription: 'When making food, not all ingredients are used 100%. Some is lost to trimming, spoilage, spillage, and cooking evaporation.',
    wastageExample: 'Example: 250g beef + 15% wastage = 287.5g deducted from inventory',
    trimmingWaste: 'Trimming & Spoilage',
    cookingEvaporation: 'Cooking Evaporation (shrinkage)',
    batchCooking: 'Batch Cooking Efficiency',
    autoWastageLearning: 'Auto-learning wastage factors from historical data',
    lowStockCritical: 'Critical - Reorder Now',
    wastageAlert: 'High Wastage Alert',
    wastageReductionTip: 'Tip: Track wastage to reduce costs by 5-15%',
    ingredientCostBreakdown: 'Ingredient Cost Breakdown',

    // ---------- EXPENSE TRACKING ----------
    expenseTracking: 'Expense Tracking',
    trackBusinessOperationalCosts: 'Track business operational costs',
    addExpense: 'Add Expense',
    expenses: 'Expenses',
    expenseCategory: 'Expense Category',
    rent: 'Rent',
    utilities: 'Utilities',
    salaries: 'Salaries',
    marketing: 'Marketing',
    maintenance: 'Maintenance',
    supplies: 'Supplies',
    transport: 'Transport',
    insurance: 'Insurance',
    taxes: 'Taxes',
    other: 'Other',
    recordedBy: 'Recorded By',
    expenseDate: 'Expense Date',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    from: 'From',
    to: 'To',
    totalExpenses: 'Total Expenses',
    averageDaily: 'Average Daily',
    perDay: 'Per day',
    categories: 'Categories',
    differentExpenseTypes: 'Different expense types',
    expenseByCategory: 'Expense by Category',
    transactions: 'transactions',
    searchExpenses: 'Search expenses...',
    noExpensesFound: 'No expenses found',
    editExpense: 'Edit Expense',
    selectCategory: 'Select category',
    optionalDescription: 'Optional description...',

    // ---------- PROFIT REPORTS ----------
    profitReports: 'Profit Reports',
    trackYourBusinessProfitability: 'Track your business profitability',
    totalRevenue: 'Total Revenue',
    totalCost: 'Total Cost',
    totalProfit: 'Total Profit',
    profitMargin: 'Profit Margin',
    dailyBreakdown: 'Daily Breakdown',
    topProducts: 'Top Products',
    byProfitContribution: 'By profit contribution',
    sold: 'Sold',
    revenue: 'Revenue',
    cost: 'Cost',
    profit: 'Profit',
    margin: 'Margin',
    averageOrder: 'Average Order',
    todayPerformance: "Today's Performance",
    revenueProfitTrend: 'Revenue & Profit Trend',
    hourlySalesTrend: 'Hourly Sales Trend',
    hour: 'Hour',
    product: 'Product',
    report: 'Report',
    generated: 'Generated',
    exportFailed: 'Failed to export',
    pdfExportError: 'PDF Export Error',
    exportExcel: 'Export Excel',
    exportPDF: 'Export PDF',
    noDataToExport: 'No data to export',
    salesReports: 'Sales Reports',
    performanceByDay: 'Performance by day',
    noSalesDataForPeriod: 'No sales data for selected period',

    // ---------- STAFF MANAGEMENT ----------
    staffManagement: 'Staff Management',
    manageStaffAccountsAndPermissions: 'Manage staff accounts and permissions',
    addStaff: 'Add Staff',
    editStaff: 'Edit Staff',
    deleteStaff: 'Delete Staff',
    fullName: 'Full Name',
    joinDate: 'Join Date',
    lastLogin: 'Last Login',
    pendingApproval: 'Pending Approval',
    active: 'Active',
    inactive: 'Inactive',
    pendingApprovals: 'Pending Approvals',
    reviewAndApproveStaffAccounts: 'Review and approve new staff account requests',
    defaultRole: 'Default Role',
    userApproved: 'User approved successfully',
    userRejected: 'User rejected',
    waitingForApproval: 'Waiting for admin approval',
    staffPerformance: 'Staff Performance',
    salesPerformance: 'Sales Performance',
    moreStaff: 'more staff members',
    noSalesData: 'No sales data available for this period',
    topPerformer: '🏆 TOP PERFORMER',
    noStaffMembersFound: 'No staff members found',
    accessDeniedOnlyOwners: 'Access denied. Only owners and admins can view staff.',
    failedToLoadStaff: 'Failed to load staff',
    staffUpdatedSuccessfully: 'Staff member updated successfully!',
    staffCreatedSuccessfully: 'Staff member created successfully!',
    failedToSaveStaff: 'Failed to save staff member',
    deleteStaffConfirm: 'Are you sure you want to delete this staff member?',
    staffDeletedSuccessfully: 'Staff member deleted successfully!',
    failedToDeleteStaff: 'Failed to delete staff member',
    roles: 'Roles',
    clickAddStaffToCreate: 'Click "Add Staff" to create a new account',
    editStaffMember: 'Edit Staff Member',
    addNewStaffMember: 'Add New Staff Member',
    enterFullName: 'Enter full name',
    enterEmailAddress: 'Enter email address',
    minimum6Characters: 'Minimum 6 characters',
    fullAccess: 'Full Access',
    operationalAccess: 'Operational Access',
    paymentOnly: 'Payment Only',
    orderTaking: 'Order Taking',
    foodPrepOnly: 'Food Prep Only',
    phoneNumber: 'Phone Number',
    optional: 'Optional',
    updateStaff: 'Update Staff',
    createStaff: 'Create Staff',
    accessDeniedOnlyOwnersAndAdmins: 'Access denied. Only owners and admins can view pending approvals.',
    failedToLoadPendingUsers: 'Failed to load pending users',
    userApprovedSuccessfully: 'User approved successfully! They can now login.',
    failedToApproveUser: 'Failed to approve user',
    rejectUserConfirm: 'Are you sure you want to reject this user?',
    userRejectedAndRemoved: 'User rejected and removed.',
    failedToRejectUser: 'Failed to reject user',
    usersWaiting: 'users waiting',
    allStaffAccountsApproved: 'All staff accounts have been approved',
    newStaffWillAppearHere: 'When new staff sign up, they will appear here',
    notProvided: 'Not provided',
    requested: 'Requested',
    assignRole: 'Assign Role',
    basicAccess: 'Basic Access',
    operations: 'Operations',
    tipApprovedUsersWillReceiveEmail: 'Approved users will receive an email notification',

    // ---------- RECIPE MANAGEMENT ----------
    recipeManagement: 'Recipe Management',
    defineProductRecipes: 'Define product recipes for automatic stock deduction',
    howRecipesWork: 'How Recipes Work',
    recipeDescription: 'Each product needs a recipe that lists all ingredients and quantities.',
    setupRecipe: 'Setup Recipe',
    viewRecipe: 'View Recipe',
    calculateCost: 'Calculate Cost',
    ingredientsNeeded: 'Ingredients Needed',
    totalIngredientCost: 'Total Ingredient Cost',
    profitSummary: 'Profit Summary',
    sellingPrice: 'Selling Price',
    ingredientCost: 'Ingredient Cost',
    recipeExists: 'Recipe configured',
    noRecipe: 'No recipe configured',
    failedToLoadRecipe: 'Failed to load recipe',
    pleaseSelectIngredientAndQuantity: 'Please select an ingredient and enter quantity',
    pleaseAddAtLeastOneIngredient: 'Please add at least one ingredient',
    recipeSavedSuccessfully: 'Recipe saved successfully!',
    failedToSaveRecipe: 'Failed to save recipe',
    noRecipeFoundForProduct: 'No recipe found for this product',
    uncategorized: 'Uncategorized',
    recipe: 'Recipe',
    noIngredientsAddedYet: 'No ingredients added yet',
    selectIngredient: 'Select Ingredient',
    quantityRequired: 'Quantity Required',
    saveRecipe: 'Save Recipe',

    // ---------- CUSTOMERS ----------
    customerManagement: 'Customer Management',
    manageCustomerAccounts: 'Manage customer accounts and loyalty',
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerDetails: 'Customer Details',
    totalCustomers: 'Total Customers',
    totalLoyaltyPoints: 'Total Loyalty Points',
    totalSpent: 'Total Spent',
    avgSpentPerCustomer: 'Average per Customer',
    searchCustomers: 'Search customers...',
    noCustomersFound: 'No customers found',
    addYourFirstCustomer: 'Add your first customer',
    customerAddress: 'Customer address',
    specialNotes: 'Special notes',
    visits: 'Visits',
    totalVisits: 'Total Visits',
    favoriteItems: 'Favorite Items',
    statistics: 'Statistics',
    points: 'points',
    customerCreated: 'Customer created successfully',
    customerUpdated: 'Customer updated successfully',
    customerDeleted: 'Customer deleted successfully',
    deleteCustomerConfirm: 'Are you sure you want to delete this customer?',

    // ---------- SETTINGS / RECEIPT ----------
    receiptFooter: 'Receipt Footer Message',
    restaurantName: 'Restaurant Name',
    address: 'Address',
    workingHours: 'Working Hours',
    taxRate: 'Tax Rate',
    configureRestaurantPreferences: 'Configure your restaurant preferences',
    settingsSavedSuccessfully: 'Settings saved successfully!',
    restaurantInformation: 'Restaurant Information',
    businessSettings: 'Business Settings',
    receiptSettings: 'Receipt Settings',
    thankYouForDining: 'Thank you for dining with us!',
    saveSettings: 'Save Settings',
    settingsSaveInfo: 'Settings are saved to your browser.',

    // ---------- REAL-TIME NOTIFICATIONS ----------
    lowStockAlert: 'Low Stock Alert',
    newOrderAlert: 'New Order Alert',
    orderReadyAlert: 'Order Ready Alert',
    salesReportReady: 'Sales Report Ready',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    newOrdersWaiting: 'new orders waiting for kitchen',
    isNow: 'is now',

    // ---------- ORDER CANCELLATION ----------
    cancelOrderTitle: 'Cancel Order',
    voidOrderTitle: 'Void Order',
    cancellationReasonPlaceholder: 'Why is this order being cancelled?',
    voidReasonPlaceholder: 'Why is this order being voided?',
    voidDescription: 'Void removes order from sales records and restores stock.',
    customerChangedMind: 'Customer changed mind',
    customerLeft: 'Customer left restaurant',
    orderTooLong: 'Order took too long',
    wrongItems: 'Wrong items ordered',
    duplicateOrder: 'Duplicate order',
    paymentIssue: 'Payment issue',
    kitchenCannotPrepare: 'Kitchen cannot prepare',
    systemError: 'System error - double charge',
    trainingError: 'Staff training error',
    testOrder: 'Test order',
    wrongTable: 'Wrong table charged',
    overcharged: 'Customer overcharged',
    cancellationReason: 'Cancellation Reason',
    yesCancel: 'Yes, Cancel',
    noKeep: 'No, Keep',
    noActiveOrder: 'No active order found.',
    couldNotFetchOrder: 'Could not fetch active order',
    pleaseAddItems: 'Please add items to order',
    itemsAdded: 'Items added to order',
    failedToAddItems: 'Failed to add items',
    addItemsToOrder: 'Add Items to Order',
    currentTotal: 'Current Total',
    newTotal: 'New Total',
    addedSuccessfully: 'Items added successfully',

    // ---------- DASHBOARD ----------
    businessPerformance: 'Business performance overview',
    todayRevenue: "Today's Revenue",
    todayProfit: "Today's Profit",
    monthRevenue: 'Month Revenue',
    monthProfit: 'Month Profit',
    netProfit: 'Net Profit',
    weeklyTrend: 'Weekly Trend',
    monthlyTrend: 'Monthly Trend',
    yearlyTrend: 'Yearly Trend',
    topSellingProducts: 'Top Selling Products',
    recentSales: 'Recent Sales',
    paymentMethods: 'Payment Methods',
    hourlySales: 'Hourly Sales',
    dailyOrders: 'Daily Orders',
    totalProducts: 'Total Products',
    needReorder: 'Need reorder',
    critical: 'Critical',
    latestTransactions: 'Latest transactions',
    cashier: 'Cashier',
    system: 'System',
    noSalesYet: 'No sales yet',
    weekRevenue: 'Week Revenue',
    gross: 'Gross',
    netProfitMargin: 'Net Profit Margin',
    quickSummary: 'Quick Summary',
    avgOrderValue: 'Avg Order Value',
    ownerDashboard: 'Owner Dashboard',
    fullBusinessAnalytics: 'Full business analytics and control',
    totalStaff: 'Total Staff',
    activeEmployees: 'Active employees',
    totalOrders: 'Total Orders',
    monthNetProfit: 'Month Net Profit',

    // ---------- MANAGER DASHBOARD ----------
    managerDashboard: 'Manager Dashboard',
    operationalOverview: 'Operational overview',
    todaySales: "Today's Sales",
    staffOnDuty: 'Staff on Duty',
    ingredientsNeedReorder: 'ingredients need reordering',
    updateInventory: 'Update Inventory',
    addOrEditStockLevels: 'Add or edit stock levels',
    viewReports: 'View Reports',
    salesAndProfitAnalytics: 'Sales and profit analytics',
    paymentSuccessful: 'Payment successful!',
    paymentFailed: 'Payment failed',
    noOrdersReady: 'No orders ready for payment',
    ordersFromKitchenWillAppear: 'Orders from kitchen will appear here',
    customer: 'Customer',
    readySince: 'Ready since',
    payment: 'Payment',
    order: 'Order',
    orderTotal: 'Order Total',
    complete: 'Complete',
    failedToUpdateOrderStatus: 'Failed to update order status',
    noOrdersToDisplay: 'No orders to display',
    ordersWillAppearHere: 'Orders will appear here when created',
    more: 'more',
    unavailable: 'Unavailable',
    dineIn: 'Dine In',
    takeaway: 'Takeaway',
    delivery: 'Delivery',
    paid: 'Paid',
    unpaid: 'Unpaid',
    pendingPayment: 'Pending Payment',
    itemsCount: 'Items Count',

    // ---------- AUTHENTICATION / LOGIN ----------
    restaurantManagementSystem: 'Restaurant Management System',
    emailAddress: 'Email Address',
    loggingIn: 'Logging in...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    demoAccounts: 'Demo Accounts',
    createAccount: 'Create your account',
    fullNamePlaceholder: 'John Doe',
    passwordMinLengthPlaceholder: 'Min 6 characters',
    passwordMinLengthHint: 'Minimum 6 characters',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    accountCreated: 'Account Created!',
    accountPendingApproval: 'Your account has been created and is pending admin approval.',
    goToLogin: 'Go to Login',
    signupFailed: 'Signup failed',
    emailPasswordRequired: 'Email and password are required',
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid email or password',
    accountPending: 'Account pending approval. Please wait.',
    accountDeactivated: 'Account deactivated. Contact admin.',
    networkError: 'Network error. Please check your connection.',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Failed to save',
    deleteConfirm: 'Are you sure you want to delete this?',
    cancelConfirm: 'Are you sure you want to cancel?',
    requiredField: 'This field is required',
    passwordMinLength: 'Password must be at least 6 characters',
    emailInvalid: 'Please enter a valid email address',
    stockInsufficient: 'Insufficient stock',

    // ---------- TIME PERIODS ----------
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last365Days: 'Last 365 Days',
    week: 'Week',
    month: 'Month',
    year: 'Year',

    // ---------- WEEK DAYS ----------
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',

    // ---------- MONTHS ----------
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',

    // ---------- SALES ----------
    sales: 'Sales',
    avgOrder: 'Avg Order',
    only: 'Only',
    customers: 'Customers',
    orderHistory: 'Order History',
    enterPhoneToViewOrders: 'Enter your phone number to view your orders',
    enterPhoneNumber: 'Enter your phone number',
    viewOrders: 'View Orders',
    customerInfo: 'Customer Information',
    noOrdersFound: 'No orders found',
    recentOrders: 'Recent Orders',
  },

  // ==========================================================
  // AMHARIC TRANSLATIONS (አማርኛ)
  // ==========================================================
  am: {
    // ---------- COMMON UI (አጠቃላይ) ----------
    dashboard: 'ዳሽቦርድ',
    logout: 'ውጣ',
    welcome: 'እንኳን ደህና መጡ',
    readyToServe: 'ደንበኞችን ለማገልገል ዝግጁ',
    search: 'ፈልግ...',
    notifications: 'ማሳወቂያዎች',
    settings: 'ቅንብሮች',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    delete: 'አጥፋ',
    edit: 'አርትዕ',
    refresh: 'አድስ',
    approve: 'ፍቀድ',
    reject: 'አትፍቀድ',
    back: 'ተመለስ',
    confirm: 'አረጋግጥ',
    loading: 'በመጫን ላይ...',
    noData: 'ምንም ውሂብ የለም',
    actions: 'ድርጊቶች',
    status: 'ሁኔታ',
    date: 'ቀን',
    time: 'ሰዓት',
    total: 'ጠቅላላ',
    amount: 'መጠን',
    description: 'መግለጫ',
    name: 'ስም',
    email: 'ኢሜይል',
    phone: 'ስልክ',
    password: 'ይለፍ ቃል',
    role: 'ሚና',
    loggedInAs: 'ገብተዋል እንደ',
    submit: 'አስገባ',
    update: 'አዘምን',
    create: 'ፍጠር',
    close: 'ዝጋ',
    export: 'ላክ',
    import: 'አምጣ',
    print: 'አትም',
    download: 'አውርድ',
    upload: 'ጫን',

    // ---------- USER ROLES (የተጠቃሚ ሚናዎች) ----------
    owner: 'ባለቤት',
    manager: 'አስተዳዳሪ',
    cashier: 'ገንዘብ ተቀባይ',
    waiter: 'አስተናጋጅ',
    kitchen: 'ኩሽና',
    admin: 'አስተዳዳሪ',
    staff: 'ሰራተኛ',

    // ---------- POS / CASHIER (የሽያጭ ነጥብ) ----------
    posTerminal: 'የሽያጭ ነጥብ',
    currentOrder:'የአሁኑ ትዕዛዝ',
    cartEmpty: 'ጋሪ ባዶ ነው',
    checkout: 'ክፈል',
    subtotal: 'ንዑስ ድምር',
    vat: 'ተጨማሪ እሴት ታክስ (15%)',
    tax: 'ግብር',
    paymentMethod: 'የክፍያ ዘዴ',
    cash: 'ጥሬ ገንዘብ',
    card:'ካርድ',
    mobile: 'ሞባይል',
    completeOrder: 'ትዕዛዝ አጠናቅቅ',
    processPayment: 'ክፍያ አካሂድ',
    customerName: 'የደንበኛ ስም',
    customerPhone: 'የደንበኛ ስልክ',
    addToCart: 'ወደ ጋሪ ጨምር',
    quantity: 'ብዛት',
    items: 'እቃዎች',
    salesHistory: 'የሽያጭ ታሪክ',
    readyForPayment: 'ለክፍያ ዝግጁ',
    addToOrder: '+ ወደ ትዕዛዝ ጨምር',
    tapToAdd: 'ለመጨመር በምናሌ ላይ ይንኩ',
    manualOrder: 'በእጅ ትዕዛዝ',
    walkInCustomer: 'ያለቀጠሮ የመጣ ደንበኛ',

    // ---------- KITCHEN (ኩሽና) ----------
    kitchenDashboard: 'የኩሽና ዳሽቦርድ',
    manageFoodPreparation: 'ምግብ ዝግጅት አስተዳድር',
    pending: 'በመጠበቅ ላይ',
    preparing: 'በዝግጅት ላይ',
    ready: 'ዝግጁ',
    completed: 'ተጠናቅቋል',
    cancelled: 'ተሰርዟል',
    startCooking: 'ማብሰል ጀምር',
    markReady: 'ዝግጁ ምልክት አድርግ',
    readyForPickup: 'ለማንሳት ዝግጁ',
    newOrderReceived: 'አዲስ ትዕዛዝ ደርሷል',
    cooking: 'በማብሰል ላይ',
    ordersToPrepare: 'ለማዘጋጀት ያሉ ትዕዛዞች',
    active: 'ንቁ',

    // ---------- WAITER / TABLE MANAGEMENT (አስተናጋጅ / ጠረጴዛ) ----------
    tableManagement: 'የጠረጴዛ አስተዳደር',
    selectTable: 'ትዕዛዝ ለመጀመር ጠረጴዛ ምረጥ',
    floorPlan: 'የሬስቶራንቱ ወለል እቅድ',
    available: 'ክፍት',
    occupied: 'ተይዟል',
    reserved: 'ተይዞል',
    cleaning: 'በጽዳት ላይ',
    capacity: 'አቅም',
    table: 'ጠረጴዛ',
    orderForTable: 'የጠረጴዛ ትዕዛዝ',
    specialInstructions: 'ልዩ መመሪያዎች',
    sendToKitchen: 'ወደ ኩሽና ላክ',
    activeOrders: 'ንቁ ትዕዛዞች',
    yourActiveOrders: 'የእርስዎ ንቁ ትዕዛዞች',
    orderNumber: 'ትዕዛዝ ቁጥር',
    cancelOrder: 'ትዕዛዝ ሰርዝ',
    addMoreItems: 'ተጨማሪ እቃዎች ጨምር',
    addItems: 'እቃዎች ጨምር',
    activeOrdersHidden: 'የተደበቁ ትዕዛዞች',
    showOrders: 'ትዕዛዞችን አሳይ',
    noActiveOrdersMessage: 'ምንም ንቁ ትዕዛዞች የሉም',
    myOrders: 'የኔ ትዕዛዞች',
    manageTables: 'ጠረጴዛዎችን እና ትዕዛዞችን አስተዳድር',
    hide: 'ደብቅ',
    clickToCreateOrder: 'ትዕዛዝ ለመፍጠር ጠቅ አድርግ',
    clickToAddItems: 'እቃዎች ለመጨመር ጠቅ አድርግ',
    newOrderForTable: 'አዲስ ትዕዛዝ ለጠረጴዛ',
    seats: 'መቀመጫዎች',
    searchMenu: 'ምናሌ ፈልግ...',
    allItems: 'ሁሉም እቃዎች',
    sending: 'በመላክ ላይ...',
    itemsToAdd: 'ለመጨመር ያሉ እቃዎች',
    noItemsSelected: 'ምንም እቃዎች አልተመረጡም',
    adding: 'በመጨመር ላይ...',
    isReserved: 'ተይዟል',
    isCleaning: 'በጽዳት ላይ ነው',
    orderSent: 'ትዕዛዝ ወደ ኩሽና ተልኳል',
    failedToSubmitOrder: 'ትዕዛዙን ማስገባት አልተቻለም',
    orderCancelledSuccess: 'ትዕዛዝ በሚገባ ተሰርዟል!',
    failedToCancelOrder: 'ትዕዛዙን መሰረዝ አልተቻለም',
    pendingConfirmations: '�ዕዛዞችን አረጋግጥ',
    tableStatus: 'የጠረጴዛ ሁኔታ',
    manageTableAvailability: 'የጠረጴዛ መኖር፣ ቦታ ማስያዝ እና የጽዳት ሁኔታ አስተዳድር',
    changeStatus: 'ሁኔታ ቀይር',
    yourAssignedTables: 'የተመደቡልዎት ጠረጴዛዎች',
    noTablesAssigned: 'ምንም ጠረጴዛዎች አልተመደቡም',
    contactManager: 'እባክዎ አስተዳዳሪዎን ያነጋግሩ',
    todaysShift: 'የዛሬ ፈረቃ',
    toConfirm: 'ማረጋገጥ',
    awaitingConfirmation: 'ማረጋገጫ በመጠበቅ ላይ',

    // ---------- QR CODE ORDERING (QR ኮድ ትዕዛዝ) ----------
    qrCodeAvailable: 'QR ኮድ አለ',
    getQRCode: 'QR ኮድ አግኝ',
    qrCodeForTable: 'የጠረጴዛ QR ኮድ',
    customersScanToOrder: 'ደንበኞች ምናሌውን ለማየት እና ለማዘዝ ይቃኛሉ',
    qrCodeInstructions: 'ይህን አገናኝ ከደንበኞች ጋር ያጋሩ። ምናሌውን ለማየት እና ለማዘዝ QR ኮዱን መቃኘት ይችላሉ።',
    qrUrl: 'QR አገናኝ',
    copyQrUrl: 'QR አገናኝ ቅዳ',
    qrNote: 'ይህን አገናኝ በመጠቀም አካላዊ QR ኮድ ማመንጨት ይችላሉ።',
    printQRCodes: 'QR ኮዶች አትም',
    generateAndPrintQRCodes: 'ለሁሉም ጠረጴዛዎች QR ኮዶች ፍጠር እና አትም',
    printAll: 'ሁሉንም አትም',
    copyUrl: 'አገናኝ ቅዳ',
    qrPrintInstructions: 'ይህን ገጽ አትመው እያንዳንዱን QR ኮድ ይቁረጡ። በተዛማጅ ጠረጴዛዎች ላይ ያድርጓቸው።',
    howQrWorks: 'QR ትዕዛዝ እንዴት ይሰራል',
    step1: 'በጠረጴዛዎ ላይ QR ኮድ ይቃኙ',
    step2: 'ምናሌውን ይመልከቱ እና እቃዎች ይጨምሩ',
    step3: 'ዝርዝሮችዎን ያስገቡ',
    step4: 'ትዕዛዝ ያስገቡ - አስተናጋጁ ያረጋግጣል',

    // ---------- INVENTORY MANAGEMENT (እቃ አስተዳደር) ----------
    inventoryManagement: 'የእቃ አስተዳደር',
    manageProductsAndIngredients: 'ምርቶችን እና ንጥረ ነገሮችን አስተዳድር',
    ingredients: 'ንጥረ ነገሮች',
    products: 'ምርቶች',
    addIngredient: 'ንጥረ ነገር ጨምር',
    addProduct: 'ምርት ጨምር',
    stock: 'ክምችት',
    minStock: 'ዝቅተኛ ክምችት',
    unit: 'ክፍል',
    unitCost: 'የአንድ ክፍል ዋጋ',
    category: 'ምድብ',
    supplier: 'አቅራቢ',
    lowStock: 'ዝቅተኛ ክምችት',
    outOfStock: 'ክምችት የለም',
    inStock: 'ክምችት አለ',
    adjustStock: 'ክምችት አስተካክል',
    currentStock: 'የአሁኑ ክምችት',
    lowStockDescription: 'የሚከተሉት ንጥረ ነገሮች ከዝቅተኛ ክምችት ደረጃ በታች ናቸው:',
    left: 'ቀርቷል',
    min: 'ዝቅተኛ',
    moreItems: 'ተጨማሪ እቃዎች',
    noIngredientsFound: 'ምንም ንጥረ ነገሮች አልተገኙም',
    noProductsFound: 'ምንም ምርቶች አልተገኙም',
    deleteFailed: 'መሰረዝ አልተቻለም',
    ingredientsBelowMinStock: 'ንጥረ ነገሮች ከዝቅተኛ ክምችት ደረጃ በታች ናቸው',
    addNew: 'አዲስ ጨምር',
    selectUnit: 'ክፍል ምረጥ',
    kilogram: 'ኪሎግራም (ኪግ)',
    gram: 'ግራም (ግ)',
    liter: 'ሊትር (ሊ)',
    milliliter: 'ሚሊሊትር (ሚሊ)',
    pieces: 'ቁራጮች (ቁራጭ)',

    // ---------- WASTAGE TRACKING (የቆሻሻ መጠን ክትትል) ----------
    wastageTracking: 'የቆሻሻ መጠን ክትትል',
    trackIngredientWaste: 'ከመቁረጥ፣ መበላሸት እና ማብሰያ የሚጠፋውን ንጥረ ነገር መከታተል',
    wastagePercentage: 'የቆሻሻ መጠን (%)',
    cookingLoss: 'የማብሰያ ኪሳራ (%)',
    yieldPercentage: 'የምርት መጠን (%)',
    expectedUsage: 'የሚጠበቀው አጠቃቀም',
    actualUsage: 'ትክክለኛ አጠቃቀም',
    wastageAmount: 'የቆሻሻ መጠን',
    wastageCost: 'የቆሻሻ ዋጋ',
    totalWastageCost: 'ጠቅላላ የቆሻሻ ዋጋ',
    wastageReport: 'የቆሻሻ ሪፖርት',
    wastageByIngredient: 'በንጥረ ነገር የቆሻሻ መጠን',
    dailyWastage: 'ቀን ቀን ቆሻሻ',
    wastageDescription: 'ምግብ በሚሰራበት ጊዜ ሁሉም ንጥረ ነገሮች መቶ በመቶ አይጠቀሙም። የተወሰነው በመቁረጥ፣ በመበላሸት እና በማብሰያ ይጠፋል።',
    wastageExample: 'ምሳሌ: 250g ሥጋ + 15% ቆሻሻ = 287.5g ከክምችት ይቀንሳል',
    trimmingWaste: 'መቁረጥ እና መበላሸት',
    cookingEvaporation: 'የማብሰያ ትነት',
    batchCooking: 'የቡድን ማብሰያ ብቃት',
    autoWastageLearning: 'ከታሪካዊ መረጃ ራስ-ተማሪ የቆሻሻ ምክንያቶች',
    lowStockCritical: 'አደገኛ - አሁን እንደገና ያዘዙ',
    wastageAlert: 'ከፍተኛ የቆሻሻ ማንቂያ',
    wastageReductionTip: 'ምክር: ወጪን በ5-15% ለመቀነስ ቆሻሻን ይከታተሉ',
    ingredientCostBreakdown: 'የንጥረ ነገር ወጪ ክፍፍል',

    // ---------- EXPENSE TRACKING (የወጪ ክትትል) ----------
    expenseTracking: 'የወጪ ክትትል',
    trackBusinessOperationalCosts: 'የንግድ ሥራ ወጪዎችን ይከታተሉ',
    addExpense: 'ወጪ ጨምር',
    expenses: 'ወጪዎች',
    expenseCategory: 'የወጪ ምድብ',
    rent: 'ኪራይ',
    utilities: 'መገልገያዎች',
    salaries: 'ደሞዝ',
    marketing: 'ግብይት',
    maintenance: 'ጥገና',
    supplies: 'አቅርቦቶች',
    transport: 'ትራንስፖርት',
    insurance: 'ኢንሹራንስ',
    taxes: 'ግብሮች',
    other: 'ሌላ',
    recordedBy: 'የመዘገበው',
    expenseDate: 'የወጪ ቀን',
    thisMonth: 'የዚህ ወር',
    thisYear: 'የዚህ ዓመት',
    from: 'ከ',
    to: 'እስከ',
    totalExpenses: 'ጠቅላላ ወጪ',
    averageDaily: 'አማካይ ቀን',
    perDay: 'በቀን',
    categories: 'ምድቦች',
    differentExpenseTypes: 'የተለያዩ የወጪ ዓይነቶች',
    expenseByCategory: 'ወጪ በምድብ',
    transactions: 'ግብይቶች',
    searchExpenses: 'ወጪዎችን ፈልግ...',
    noExpensesFound: 'ምንም ወጪዎች አልተገኙም',
    editExpense: 'ወጪ አርትዕ',
    selectCategory: 'ምድብ ምረጥ',
    optionalDescription: 'አማራጭ መግለጫ...',

    // ---------- PROFIT REPORTS (የትርፍ ሪፖርቶች) ----------
    profitReports: 'የትርፍ ሪፖርቶች',
    trackYourBusinessProfitability: 'የንግድዎን ትርፋማነት ይከታተሉ',
    totalRevenue: 'ጠቅላላ ገቢ',
    totalCost: 'ጠቅላላ ወጪ',
    totalProfit: 'ጠቅላላ ትርፍ',
    profitMargin: 'የትርፍ ህዳግ',
    dailyBreakdown: 'ዕለታዊ ክፍፍል',
    topProducts: 'ከፍተኛ ምርቶች',
    byProfitContribution: 'በትርፍ አስተዋጽኦ',
    sold: 'ተሽጧል',
    revenue: 'ገቢ',
    cost: 'ወጪ',
    profit: 'ትርፍ',
    margin: 'ህዳግ',
    averageOrder: 'አማካይ ትዕዛዝ',
    todayPerformance: "የዛሬ አፈጻጸም",
    revenueProfitTrend: 'የገቢ እና ትርፍ አዝማሚያ',
    hourlySalesTrend: 'የሰዓት ሽያጭ አዝማሚያ',
    hour: 'ሰዓት',
    product: 'ምርት',
    report: 'ሪፖርት',
    generated: 'ተፈጥሯል',
    exportFailed: 'ወደ ውጭ መላክ አልተሳካም',
    pdfExportError: 'PDF የወጪ ስህተት',
    exportExcel: 'Excel ላክ',
    exportPDF: 'PDF ላክ',
    noDataToExport: 'ለመላክ ምንም ውሂብ የለም',
    salesReports: 'የሽያጭ ሪፖርቶች',
    performanceByDay: 'አፈጻጸም በቀን',
    noSalesDataForPeriod: 'ለተመረጠው ጊዜ ምንም የሽያጭ ውሂብ የለም',

    // ---------- STAFF MANAGEMENT (የሰራተኛ አስተዳደር) ----------
    staffManagement: 'የሰራተኛ አስተዳደር',
    manageStaffAccountsAndPermissions: 'የሰራተኛ መለያዎችን እና ፈቃዶችን ያስተዳድሩ',
    addStaff: 'ሰራተኛ ጨምር',
    editStaff: 'ሰራተኛ አርትዕ',
    deleteStaff: 'ሰራተኛ ሰርዝ',
    fullName: 'ሙሉ ስም',
    joinDate: 'የተቀላቀሉበት ቀን',
    lastLogin: 'የመጨረሻ መግቢያ',
    pendingApproval: 'በመጠባበቅ ላይ',
    active: 'ንቁ',
    inactive: 'ንቁ ያልሆነ',
    pendingApprovals: 'በመጠባበቅ ላይ ያሉ',
    reviewAndApproveStaffAccounts: 'አዳዲስ የሰራተኛ መለያ ጥያቄዎችን ይገምግሙ እና ያፅድቁ',
    defaultRole: 'ነባር ሚና',
    userApproved: 'ተጠቃሚ በሚገባ ጸድቋል',
    userRejected: 'ተጠቃሚ ውድቅ ተደርጓል',
    waitingForApproval: 'የአስተዳዳሪ ማጽደቅ በመጠባበቅ ላይ',
    staffPerformance: 'የሰራተኛ አፈጻጸም',
    salesPerformance: 'የሽያጭ አፈጻጸም',
    moreStaff: 'ተጨማሪ ሰራተኞች',
    noSalesData: 'ለዚህ ጊዜ ምንም የሽያጭ ውሂብ የለም',
    topPerformer: '🏆 ከፍተኛ አፈጻጸም',
    noStaffMembersFound: 'ምንም ሰራተኞች አልተገኙም',
    accessDeniedOnlyOwners: 'መዳረሻ ተከልክሏል። ባለቤቶች እና አስተዳዳሪዎች ብቻ ሰራተኞችን ማየት ይችላሉ።',
    failedToLoadStaff: 'ሰራተኞችን ማግኘት አልተቻለም',
    staffUpdatedSuccessfully: 'ሰራተኛ በሚገባ ተዘምኗል!',
    staffCreatedSuccessfully: 'ሰራተኛ በሚገባ ተፈጥሯል!',
    failedToSaveStaff: 'ሰራተኛን ማስቀመጥ አልተቻለም',
    deleteStaffConfirm: 'ይህን ሰራተኛ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    staffDeletedSuccessfully: 'ሰራተኛ በሚገባ ተሰርዟል!',
    failedToDeleteStaff: 'ሰራተኛን መሰረዝ አልተቻለም',
    roles: 'ሚናዎች',
    clickAddStaffToCreate: 'አዲስ መለያ ለመፍጠር "ሰራተኛ ጨምር" ን ጠቅ ያድርጉ',
    editStaffMember: 'ሰራተኛ አርትዕ',
    addNewStaffMember: 'አዲስ ሰራተኛ ጨምር',
    enterFullName: 'ሙሉ ስም ያስገቡ',
    enterEmailAddress: 'ኢሜይል አድራሻ ያስገቡ',
    minimum6Characters: 'ቢያንስ 6 ቁምፊዎች',
    fullAccess: 'ሙሉ መዳረሻ',
    operationalAccess: 'የስራ መዳረሻ',
    paymentOnly: 'ክፍያ ብቻ',
    orderTaking: 'ትዕዛዝ መውሰድ',
    foodPrepOnly: 'ምግብ ዝግጅት ብቻ',
    phoneNumber: 'ስልክ ቁጥር',
    optional: 'አማራጭ',
    updateStaff: 'ሰራተኛ አዘምን',
    createStaff: 'ሰራተኛ ፍጠር',
    accessDeniedOnlyOwnersAndAdmins: 'መዳረሻ ተከልክሏል። ባለቤቶች እና አስተዳዳሪዎች ብቻ በመጠባበቅ ላይ ያሉትን ማየት ይችላሉ።',
    failedToLoadPendingUsers: 'በመጠባበቅ ላይ ያሉ ተጠቃሚዎችን ማግኘት አልተቻለም',
    userApprovedSuccessfully: 'ተጠቃሚ በሚገባ ጸድቋል! አሁን መግባት ይችላሉ።',
    failedToApproveUser: 'ተጠቃሚን ማጽደቅ አልተቻለም',
    rejectUserConfirm: 'ይህን ተጠቃሚ ውድቅ ማድረግ እንደሚፈልጉ እርግጠኛ ነዎት?',
    userRejectedAndRemoved: 'ተጠቃሚ ውድቅ ተደርጓል እና ተወግዷል።',
    failedToRejectUser: 'ተጠቃሚን ውድቅ ማድረግ አልተቻለም',
    usersWaiting: 'ተጠቃሚዎች በመጠባበቅ ላይ',
    allStaffAccountsApproved: 'ሁሉም የሰራተኛ መለያዎች ጸድቀዋል',
    newStaffWillAppearHere: 'አዲስ ሰራተኞች ሲመዘገቡ እዚህ ይታያሉ',
    notProvided: 'አልቀረበም',
    requested: 'የተጠየቀ',
    assignRole: 'ሚና መድብ',
    basicAccess: 'መሰረታዊ መዳረሻ',
    operations: 'ስራዎች',
    tipApprovedUsersWillReceiveEmail: 'የጸደቁ ተጠቃሚዎች የኢሜይል ማሳወቂያ ይቀበላሉ',

    // ---------- RECIPE MANAGEMENT (የምግብ አዘገጃጀት አስተዳደር) ----------
    recipeManagement: 'የምግብ አዘገጃጀት አስተዳደር',
    defineProductRecipes: 'ለራስ-ሰር ክምችት መቀነስ የምርት የምግብ አዘገጃጀቶችን ይግለጹ',
    howRecipesWork: 'የምግብ አዘገጃጀቶች እንዴት ይሰራሉ',
    recipeDescription: 'እያንዳንዱ ምርት ሁሉንም ንጥረ ነገሮች እና መጠኖች የሚዘረዝር የምግብ አዘገጃጀት ይፈልጋል።',
    setupRecipe: 'የምግብ አዘገጃጀት አዘጋጅ',
    viewRecipe: 'የምግብ አዘገጃጀት ተመልከት',
    calculateCost: 'ወጪ አስላ',
    ingredientsNeeded: 'የሚፈለጉ ንጥረ ነገሮች',
    totalIngredientCost: 'ጠቅላላ የንጥረ ነገር ወጪ',
    profitSummary: 'የትርፍ ማጠቃለያ',
    sellingPrice: 'የሽያጭ ዋጋ',
    ingredientCost: 'የንጥረ ነገር ወጪ',
    recipeExists: 'የምግብ አዘገጃጀት ተዘጋጅቷል',
    noRecipe: 'ምንም የምግብ አዘገጃጀት አልተዘጋጀም',
    failedToLoadRecipe: 'የምግብ አዘገጃጀት ማግኘት አልተቻለም',
    pleaseSelectIngredientAndQuantity: 'እባክዎ ንጥረ ነገር ይምረጡ እና መጠን ያስገቡ',
    pleaseAddAtLeastOneIngredient: 'እባክዎ ቢያንስ አንድ ንጥረ ነገር ይጨምሩ',
    recipeSavedSuccessfully: 'የምግብ አዘገጃጀት በሚገባ ተቀምጧል!',
    failedToSaveRecipe: 'የምግብ አዘገጃጀት ማስቀመጥ አልተቻለም',
    noRecipeFoundForProduct: 'ለዚህ ምርት ምንም የምግብ አዘገጃጀት አልተገኘም',
    uncategorized: 'ምድብ ያልተደረገ',
    recipe: 'የምግብ አዘገጃጀት',
    noIngredientsAddedYet: 'እስካሁን ምንም ንጥረ ነገሮች አልተጨመሩም',
    selectIngredient: 'ንጥረ ነገር ምረጥ',
    quantityRequired: 'የሚፈለገው መጠን',
    saveRecipe: 'የምግብ አዘገጃጀት አስቀምጥ',

    // ---------- CUSTOMERS (ደንበኞች) ----------
    customerManagement: 'የደንበኛ አስተዳደር',
    manageCustomerAccounts: 'የደንበኛ መለያዎችን እና ታማኝነት ያስተዳድሩ',
    addCustomer: 'ደንበኛ ጨምር',
    editCustomer: 'ደንበኛ አርትዕ',
    deleteCustomer: 'ደንበኛ ሰርዝ',
    customerDetails: 'የደንበኛ ዝርዝሮች',
    totalCustomers: 'ጠቅላላ ደንበኞች',
    totalLoyaltyPoints: 'ጠቅላላ የታማኝነት ነጥቦች',
    totalSpent: 'ጠቅላላ ወጪ ያደረገው',
    avgSpentPerCustomer: 'አማካይ በአንድ ደንበኛ',
    searchCustomers: 'ደንበኞችን ፈልግ...',
    noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
    addYourFirstCustomer: 'የመጀመሪያ ደንበኛዎን ይጨምሩ',
    customerAddress: 'የደንበኛ አድራሻ',
    specialNotes: 'ልዩ ማስታወሻዎች',
    visits: 'ጉብኝቶች',
    totalVisits: 'ጠቅላላ ጉብኝቶች',
    favoriteItems: 'ተወዳጅ እቃዎች',
    statistics: 'ስታቲስቲክስ',
    points: 'ነጥቦች',
    customerCreated: 'ደንበኛ በሚገባ ተፈጥሯል',
    customerUpdated: 'ደንበኛ በሚገባ ተዘምኗል',
    customerDeleted: 'ደንበኛ በሚገባ ተሰርዟል',
    deleteCustomerConfirm: 'ይህን ደንበኛ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',

    // ---------- SETTINGS / RECEIPT (ቅንብሮች / ደረሰኝ) ----------
    receiptFooter: 'የደረሰኝ የግርጌ መልዕክት',
    restaurantName: 'የሬስቶራንት ስም',
    address: 'አድራሻ',
    workingHours: 'የስራ ሰዓት',
    taxRate: 'የግብር መጠን',
    configureRestaurantPreferences: 'የሬስቶራንትዎን ምርጫዎች ያዋቅሩ',
    settingsSavedSuccessfully: 'ቅንብሮች በሚገባ ተቀምጠዋል!',
    restaurantInformation: 'የሬስቶራንት መረጃ',
    businessSettings: 'የንግድ ቅንብሮች',
    receiptSettings: 'የደረሰኝ ቅንብሮች',
    thankYouForDining: 'እንደተመገቡ እናመሰግናለን!',
    saveSettings: 'ቅንብሮችን አስቀምጥ',
    settingsSaveInfo: 'ቅንብሮች በአሳሽዎ ውስጥ ተቀምጠዋል።',

    // ---------- REAL-TIME NOTIFICATIONS (የቅጽበታዊ ማሳወቂያዎች) ----------
    lowStockAlert: 'ዝቅተኛ ክምችት ማንቂያ',
    newOrderAlert: 'አዲስ ትዕዛዝ ማንቂያ',
    orderReadyAlert: 'ትዕዛዝ ዝግጁ ማንቂያ',
    salesReportReady: 'የሽያጭ ሪፖርት ዝግጁ',
    markAllRead: 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    noNotifications: 'ምንም ማሳወቂያዎች የሉም',
    newOrdersWaiting: 'አዲስ ትዕዛዞች ለኩሽና በመጠበቅ ላይ',
    isNow: 'አሁን ነው',

    // ---------- ORDER CANCELLATION (ትዕዛዝ መሰረዝ) ----------
    cancelOrderTitle: 'ትዕዛዝ ሰርዝ',
    voidOrderTitle: 'ትዕዛዝ ባዶ አድርግ',
    cancellationReasonPlaceholder: 'ይህ ትዕዛዝ የተሰረዘው ለምንድነው?',
    voidReasonPlaceholder: 'ይህ ትዕዛዝ ባዶ የሚደረገው ለምንድነው?',
    voidDescription: 'ባዶ ማለት ይህ ትዕዛዝ ከሽያጭ መዝገቦች ሙሉ በሙሉ ይወገዳል እና ክምችት ይመለሳል።',
    customerChangedMind: 'ደንበኛ ሀሳቡን ቀይሯል',
    customerLeft: 'ደንበኛ ሬስቶራንቱን ለቋል',
    orderTooLong: 'ትዕዛዝ ብዙ ጊዜ ወስዷል',
    wrongItems: 'የተሳሳቱ እቃዎች ታዘዋል',
    duplicateOrder: 'የተደገመ ትዕዛዝ',
    paymentIssue: 'የክፍያ ችግር',
    kitchenCannotPrepare: 'ኩሽና ማዘጋጀት አይችልም',
    systemError: 'የስርዓት ስህተት - ድርብ ክፍያ',
    trainingError: 'የሰራተኛ ስልጠና ስህተት',
    testOrder: 'የሙከራ ትዕዛዝ',
    wrongTable: 'የተሳሳተ ጠረጴዛ ተከፍሏል',
    overcharged: 'ደንበኛ ከመጠን በላይ ተከፍሏል',
    cancellationReason: 'የመሰረዝ ምክንያት',
    yesCancel: 'አዎ, ሰርዝ',
    noKeep: 'አይ, አትሰርዝ',
    noActiveOrder: 'ምንም ንቁ ትዕዛዝ አልተገኘም።',
    couldNotFetchOrder: 'ንቁ ትዕዛዝ ማግኘት አልተቻለም',
    pleaseAddItems: 'እባክዎ እቃዎችን ወደ ትዕዛዝ ይጨምሩ',
    itemsAdded: 'እቃዎች ወደ ትዕዛዝ ተጨምረዋል',
    failedToAddItems: 'እቃዎችን መጨመር አልተቻለም',
    addItemsToOrder: 'ወደ ትዕዛዝ እቃዎች ጨምር',
    currentTotal: 'የአሁኑ ጠቅላላ',
    newTotal: 'አዲስ ጠቅላላ',
    addedSuccessfully: 'እቃዎች በሚገባ ተጨምረዋል',

    // ---------- DASHBOARD (ዳሽቦርድ) ----------
    businessPerformance: 'የንግድ አፈጻጸም አጠቃላይ እይታ',
    todayRevenue: "የዛሬ ገቢ",
    todayProfit: "የዛሬ ትርፍ",
    monthRevenue: 'የወር ገቢ',
    monthProfit: 'የወር ትርፍ',
    netProfit: 'የተጣራ ትርፍ',
    weeklyTrend: 'ሳምንታዊ አዝማሚያ',
    monthlyTrend: 'ወርሃዊ አዝማሚያ',
    yearlyTrend: 'ዓመታዊ አዝማሚያ',
    topSellingProducts: 'ከፍተኛ ሽያጭ ያላቸው ምርቶች',
    recentSales: 'የቅርብ ጊዜ ሽያጮች',
    paymentMethods: 'የክፍያ ዘዴዎች',
    hourlySales: 'የሰዓት ሽያጮች',
    dailyOrders: 'ዕለታዊ ትዕዛዞች',
    totalProducts: 'ጠቅላላ ምርቶች',
    needReorder: 'እንደገና ማዘዝ ያስፈልጋል',
    critical: 'ወሳኝ',
    latestTransactions: 'የቅርብ ጊዜ ግብይቶች',
    cashier: 'ገንዘብ ተቀባይ',
    system: 'ስርዓት',
    noSalesYet: 'እስካሁን ሽያጭ የለም',
    weekRevenue: 'የሳምንት ገቢ',
    gross: 'ጠቅላላ',
    netProfitMargin: 'የተጣራ ትርፍ ህዳግ',
    quickSummary: 'ፈጣን ማጠቃለያ',
    avgOrderValue: 'አማካይ የትዕዛዝ ዋጋ',
    ownerDashboard: 'የባለቤት ዳሽቦርድ',
    fullBusinessAnalytics: 'ሙሉ የንግድ ትንተና እና ቁጥጥር',
    totalStaff: 'ጠቅላላ ሰራተኞች',
    activeEmployees: 'ንቁ ሰራተኞች',
    totalOrders: 'ጠቅላላ ትዕዛዞች',
    monthNetProfit: 'የወር የተጣራ ትርፍ',

    // ---------- MANAGER DASHBOARD (የአስተዳዳሪ ዳሽቦርድ) ----------
    managerDashboard: 'የአስተዳዳሪ ዳሽቦርድ',
    operationalOverview: 'የስራ አጠቃላይ እይታ',
    todaySales: "የዛሬ ሽያጭ",
    staffOnDuty: 'በስራ ላይ ያሉ ሰራተኞች',
    ingredientsNeedReorder: 'ንጥረ ነገሮች እንደገና ማዘዝ ያስፈልጋቸዋል',
    updateInventory: 'ክምችት አዘምን',
    addOrEditStockLevels: 'የክምችት ደረጃዎችን ይጨምሩ ወይም ያርትዑ',
    viewReports: 'ሪፖርቶችን ተመልከት',
    salesAndProfitAnalytics: 'የሽያጭ እና ትርፍ ትንተና',
    paymentSuccessful: 'ክፍያ ተሳክቷል!',
    paymentFailed: 'ክፍያ አልተሳካም',
    noOrdersReady: 'ለክፍያ ዝግጁ የሆኑ ምንም ትዕዛዞች የሉም',
    ordersFromKitchenWillAppear: 'ከኩሽና ትዕዛዞች እዚህ ይታያሉ',
    customer: 'ደንበኛ',
    readySince: 'ዝግጁ የሆነው ከ',
    payment: 'ክፍያ',
    order: 'ትዕዛዝ',
    orderTotal: 'ጠቅላላ ትዕዛዝ',
    complete: 'አጠናቅቅ',
    failedToUpdateOrderStatus: 'የትዕዛዝ ሁኔታ ማዘመን አልተቻለም',
    noOrdersToDisplay: 'ለማሳየት ምንም ትዕዛዞች የሉም',
    ordersWillAppearHere: 'ትዕዛዞች ሲፈጠሩ እዚህ ይታያሉ',
    more: 'ተጨማሪ',
    unavailable: 'አይገኝም',
    dineIn: 'እዚህ ተመግበው',
    takeaway: 'ይውሰዱ',
    delivery: 'ማድረስ',
    paid: 'ተከፍሏል',
    unpaid: 'አልተከፈለም',
    pendingPayment: 'በመጠባበቅ ላይ',

    // ---------- AUTHENTICATION / LOGIN (ማረጋገጫ / መግቢያ) ----------
    restaurantManagementSystem: 'የሬስቶራንት አስተዳደር ስርዓት',
    emailAddress: 'ኢሜይል አድራሻ',
    loggingIn: 'በመግባት ላይ...',
    signIn: 'ግባ',
    noAccount: 'መለያ የለዎትም?',
    signUp: 'ተመዝገብ',
    demoAccounts: 'የማሳያ መለያዎች',
    createAccount: 'መለያዎን ይፍጠሩ',
    fullNamePlaceholder: 'ሙሉ ስም',
    passwordMinLengthPlaceholder: 'ቢያንስ 6 ቁምፊዎች',
    passwordMinLengthHint: 'ቢያንስ 6 ቁምፊዎች',
    creatingAccount: 'መለያ በመፍጠር ላይ...',
    alreadyHaveAccount: 'አስቀድመው መለያ አለዎት?',
    accountCreated: 'መለያ ተፈጥሯል!',
    accountPendingApproval: 'መለያዎ ተፈጥሯል እና በአስተዳዳሪ ማጽደቅ ላይ ነው።',
    goToLogin: 'ወደ መግቢያ ሂድ',
    signupFailed: 'ምዝገባ አልተሳካም',
    emailPasswordRequired: 'ኢሜይል እና ይለፍ ቃል ያስፈልጋሉ',
    loginFailed: 'መግባት አልተቻለም',
    invalidCredentials: 'የተሳሳተ ኢሜይል ወይም ይለፍ ቃል',
    accountPending: 'መለያ በማጽደቅ ላይ ነው። እባክዎ ይጠብቁ።',
    accountDeactivated: 'መለያ ተሰርዟል። አስተዳዳሪን ያነጋግሩ።',
    networkError: 'የአውታረ መረብ ስህተት። እባክዎ ግንኙነትዎን ያረጋግጡ።',
    saveSuccess: 'በሚገባ ተቀምጧል',
    saveFailed: 'ማስቀመጥ አልተቻለም',
    deleteConfirm: 'ይህን መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    cancelConfirm: 'መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    requiredField: 'ይህ መስክ ያስፈልጋል',
    passwordMinLength: 'ይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
    stockInsufficient: 'በቂ ክምችት የለም',

    // ---------- TIME PERIODS (የጊዜ ክልሎች) ----------
    last7Days: 'ያለፉት 7 ቀናት',
    last30Days: 'ያለፉት 30 ቀናት',
    last365Days: 'ያለፉት 365 ቀናት',
    week: 'ሳምንት',
    month: 'ወር',
    year: 'ዓመት',

    // ---------- WEEK DAYS (የሳምንቱ ቀናት) ----------
    monday: 'ሰኞ',
    tuesday: 'ማክሰኞ',
    wednesday: 'ረቡዕ',
    thursday: 'ሐሙስ',
    friday: 'ዓርብ',
    saturday: 'ቅዳሜ',
    sunday: 'እሑድ',

    // ---------- MONTHS (ወራት) ----------
    january: 'ጥር',
    february: 'የካቲት',
    march: 'መጋቢት',
    april: 'ሚያዝያ',
    may: 'ግንቦት',
    june: 'ሰኔ',
    july: 'ሐምሌ',
    august: 'ነሐሴ',
    september: 'መስከረም',
    october: 'ጥቅምት',
    november: 'ህዳር',
    december: 'ታህሳስ',

    // ---------- SALES (ሽያጮች) ----------
    sales: 'ሽያጮች',
    avgOrder: 'አማካይ ትዕዛዝ',
    only: 'ብቻ',
    customers: 'ደንበኞች',
    orderHistory: 'የትዕዛዝ ታሪክ',
    enterPhoneToViewOrders: 'ትዕዛዞችዎን ለማየት ስልክ ቁጥርዎን ያስገቡ',
    enterPhoneNumber: 'ስልክ ቁጥርዎን ያስገቡ',
    viewOrders: 'ትዕዛዞችን ይመልከቱ',
    customerInfo: 'የደንበኛ መረጃ',
    noOrdersFound: 'ምንም ትዕዛዞች አልተገኙም',
    recentOrders: 'የቅርብ ጊዜ ትዕዛዞች',
  },
};

// ============================================================
// LANGUAGE CONTEXT PROVIDER
// ============================================================
const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  // Initialize language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function - returns the translated text for a given key
  // Falls back to English if translation doesn't exist in current language
  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};