import React, { createContext, useState, useContext, useEffect } from 'react';

/**
 * ============================================================
 * LANGUAGE TRANSLATIONS FOR ETHIOPIAN RESTAURANT POS SYSTEM
 * ============================================================
 * 
 * This file contains all translations for the entire POS system.
 * Supported languages:
 *   - English (en) - Default
 *   - Amharic (am) - አማርኛ
 * 
 * How to use in components:
 *   import { useLanguage } from '../context/LanguageContext';
 *   const { t, language, setLanguage } = useLanguage();
 *   <h1>{t('dashboard')}</h1>
 * 
 * To add a new language, add a new object inside translations{}.
 * ============================================================
 */

const translations = {
  
  // ============================================================
  // ENGLISH TRANSLATIONS (Default)
  // ============================================================
  en: {
    // -------------------- COMMON UI ELEMENTS --------------------
    dashboard: 'Dashboard',
    logout: 'Logout',
    welcome: 'Welcome back',
    readyToServe: 'Ready to serve customers',
    search: 'Search...',
    notifications: 'Notifications',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    refresh: 'Refresh',
    approve: 'Approve',
    reject: 'Reject',
    back: 'Back',
    confirm: 'Confirm',
    loading: 'Loading...',
    noData: 'No data available',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    total: 'Total',
    amount: 'Amount',
    description: 'Description',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    role: 'Role',
    loggedInAs: 'Logged in as',
    
    // -------------------- USER ROLES --------------------
    owner: 'Owner',
    manager: 'Manager',
    cashier: 'Cashier',
    waiter: 'Waiter',
    kitchen: 'Kitchen',
    admin: 'Admin',
    staff: 'Staff',
    
    // -------------------- POS / CASHIER MODULE --------------------
    posTerminal: 'POS Terminal',
    currentOrder: 'Current Order',
    cartEmpty: 'Cart is empty',
    checkout: 'Checkout',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    tax: 'Tax',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    mobile: 'Mobile',
    completeOrder: 'Complete Order',
    processPayment: 'Process Payment',
    customerName: 'Customer name',
    customerPhone: 'Customer phone',
    addToCart: 'Add to Cart',
    quantity: 'Quantity',
    items: 'Items',
    salesHistory: 'Sales History',
    readyForPayment: 'Ready for Payment',
    addToOrder: '+ Add to order',
    tapToAdd: 'Tap on menu items to add',
    
    // -------------------- KITCHEN MODULE --------------------
    kitchenDashboard: 'Kitchen Dashboard',
    manageFoodPreparation: 'Manage food preparation',
    pending: 'Pending',
    preparing: 'Preparing',
    ready: 'Ready',
    completed: 'Completed',
    cancelled: 'Cancelled',
    startCooking: 'Start Cooking',
    markReady: 'Mark Ready',
    readyForPickup: 'Ready for Pickup',
    newOrderReceived: 'New order received',
    cooking: 'Cooking',
    ordersToPrepare: 'Orders to prepare',
    
    // -------------------- WAITER / TABLE MANAGEMENT --------------------
    tableManagement: 'Table Management',
    selectTable: 'Select a table to start an order',
    floorPlan: 'Restaurant Floor Plan',
    available: 'Available',
    occupied: 'Occupied',
    reserved: 'Reserved',
    cleaning: 'Cleaning',
    capacity: 'Cap',
    table: 'Table',
    orderForTable: 'Order for Table',
    specialInstructions: 'Special instructions',
    sendToKitchen: 'Send to Kitchen',
    activeOrders: 'Active Orders',
    yourActiveOrders: 'Your Active Orders',
    orderNumber: 'Order Number',
    cancelOrder: 'Cancel Order',
    addMoreItems: 'Add More Items',
    addItems: 'Add Items',
    activeOrdersHidden: 'Hidden Orders',
    showOrders: 'Show Orders',
    noActiveOrdersMessage: 'No active orders',
    myOrders: 'My Orders',
    manageTables: 'Manage your restaurant tables and orders',
    hide: 'Hide',
    clickToCreateOrder: 'Click to create order',
    clickToAddItems: 'Click to add items',
    newOrderForTable: 'New Order for Table',
    seats: 'seats',
    searchMenu: 'Search menu...',
    allItems: 'All Items',
    sending: 'Sending...',
    itemsToAdd: 'Items to Add',
    noItemsSelected: 'No items selected',
    adding: 'Adding...',
    isReserved: 'is reserved',
    isCleaning: 'is being cleaned',
    orderSent: 'Order sent to kitchen',
    failedToSubmitOrder: 'Failed to submit order',
    orderCancelledSuccess: 'Order cancelled successfully!',
    failedToCancelOrder: 'Failed to cancel order',
    
    // -------------------- INVENTORY MANAGEMENT --------------------
    inventoryManagement: 'Inventory Management',
    manageProductsAndIngredients: 'Manage products and ingredients',
    ingredients: 'Ingredients',
    products: 'Products',
    addIngredient: 'Add Ingredient',
    addProduct: 'Add Product',
    stock: 'Stock',
    minStock: 'Min Stock',
    unit: 'Unit',
    unitCost: 'Unit Cost',
    category: 'Category',
    supplier: 'Supplier',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    adjustStock: 'Adjust Stock',
    currentStock: 'Current Stock',
    lowStockDescription: 'The following ingredients are below minimum stock level:',
    left: 'left',
    min: 'Min',
    moreItems: 'more items',
    
    // -------------------- EXPENSE TRACKING --------------------
    expenseTracking: 'Expense Tracking',
    trackBusinessOperationalCosts: 'Track business operational costs',
    addExpense: 'Add Expense',
    expenses: 'Expenses',
    expenseCategory: 'Expense Category',
    rent: 'Rent',
    utilities: 'Utilities',
    salaries: 'Salaries',
    marketing: 'Marketing',
    maintenance: 'Maintenance',
    supplies: 'Supplies',
    transport: 'Transport',
    insurance: 'Insurance',
    taxes: 'Taxes',
    other: 'Other',
    recordedBy: 'Recorded By',
    expenseDate: 'Expense Date',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    from: 'From',
    to: 'To',
    totalExpenses: 'Total Expenses',
    averageDaily: 'Average Daily',
    perDay: 'Per day',
    categories: 'Categories',
    differentExpenseTypes: 'Different expense types',
    expenseByCategory: 'Expense by Category',
    transactions: 'transactions',
    searchExpenses: 'Search expenses...',
    noExpensesFound: 'No expenses found',
    editExpense: 'Edit Expense',
    selectCategory: 'Select category',
    optionalDescription: 'Optional description...',
    
    // -------------------- PROFIT REPORTS --------------------
    profitReports: 'Profit Reports',
    trackYourBusinessProfitability: 'Track your business profitability',
    totalRevenue: 'Total Revenue',
    totalCost: 'Total Cost',
    totalProfit: 'Total Profit',
    profitMargin: 'Profit Margin',
    dailyBreakdown: 'Daily Breakdown',
    topProducts: 'Top Products',
    byProfitContribution: 'By profit contribution',
    sold: 'Sold',
    revenue: 'Revenue',
    cost: 'Cost',
    profit: 'Profit',
    margin: 'Margin',
    averageOrder: 'Average Order',
    todayPerformance: "Today's Performance",
    revenueProfitTrend: 'Revenue & Profit Trend',
    hourlySalesTrend: 'Hourly Sales Trend',
    hour: 'Hour',
    product: 'Product',
    report: 'Report',
    generated: 'Generated',
    exportFailed: 'Failed to export',
    pdfExportError: 'PDF Export Error',
    exportExcel: 'Export Excel',
    exportPDF: 'Export PDF',
    noDataToExport: 'No data to export',
    salesReports: 'Sales Reports',
    profit: 'Profit',
    performanceByDay: 'Performance by day',
    noSalesDataForPeriod: 'No sales data for selected period',
    
    // -------------------- STAFF MANAGEMENT --------------------
    staffManagement: 'Staff Management',
    manageStaffAccountsAndPermissions: 'Manage staff accounts and permissions',
    addStaff: 'Add Staff',
    editStaff: 'Edit Staff',
    deleteStaff: 'Delete Staff',
    fullName: 'Full Name',
    joinDate: 'Join Date',
    lastLogin: 'Last Login',
    pendingApproval: 'Pending Approval',
    active: 'Active',
    inactive: 'Inactive',
    pendingApprovals: 'Pending Approvals',
    reviewAndApproveStaffAccounts: 'Review and approve new staff account requests',
    defaultRole: 'Default Role',
    userApproved: 'User approved successfully',
    userRejected: 'User rejected',
    waitingForApproval: 'Waiting for admin approval',
    staffPerformance: 'Staff Performance',
    salesPerformance: 'Sales Performance',
    moreStaff: 'more staff members',
    noSalesData: 'No sales data available for this period',
    topPerformer: '🏆 TOP PERFORMER',
    noStaffMembersFound: 'No staff members found',
    accessDeniedOnlyOwners: 'Access denied. Only owners and admins can view staff.',
    failedToLoadStaff: 'Failed to load staff',
    staffUpdatedSuccessfully: 'Staff member updated successfully!',
    staffCreatedSuccessfully: 'Staff member created successfully! They will need admin approval.',
    failedToSaveStaff: 'Failed to save staff member',
    deleteStaffConfirm: 'Are you sure you want to delete this staff member? This action cannot be undone.',
    staffDeletedSuccessfully: 'Staff member deleted successfully!',
    failedToDeleteStaff: 'Failed to delete staff member',
    roles: 'Roles',
    clickAddStaffToCreate: 'Click "Add Staff" to create a new account',
    editStaffMember: 'Edit Staff Member',
    addNewStaffMember: 'Add New Staff Member',
    enterFullName: 'Enter full name',
    enterEmailAddress: 'Enter email address',
    minimum6Characters: 'Minimum 6 characters',
    fullAccess: 'Full Access',
    operationalAccess: 'Operational Access',
    paymentOnly: 'Payment Only',
    orderTaking: 'Order Taking',
    foodPrepOnly: 'Food Prep Only',
    phoneNumber: 'Phone Number',
    optional: 'Optional',
    updateStaff: 'Update Staff',
    createStaff: 'Create Staff',
    accessDeniedOnlyOwnersAndAdmins: 'Access denied. Only owners and admins can view pending approvals.',
    failedToLoadPendingUsers: 'Failed to load pending users',
    userApprovedSuccessfully: 'User approved successfully! They can now login.',
    failedToApproveUser: 'Failed to approve user',
    rejectUserConfirm: 'Are you sure you want to reject this user? They will be removed from the system.',
    userRejectedAndRemoved: 'User rejected and removed.',
    failedToRejectUser: 'Failed to reject user',
    usersWaiting: 'users waiting',
    noPendingApprovals: 'No pending approvals',
    allStaffAccountsApproved: 'All staff accounts have been approved',
    newStaffWillAppearHere: 'When new staff sign up, they will appear here',
    notProvided: 'Not provided',
    requested: 'Requested',
    assignRole: 'Assign Role',
    basicAccess: 'Basic Access',
    operations: 'Operations',
    tipApprovedUsersWillReceiveEmail: 'Approved users will receive an email notification (if configured) and can immediately login with their credentials.',
    
    // -------------------- RECIPE MANAGEMENT --------------------
    recipeManagement: 'Recipe Management',
    defineProductRecipes: 'Define product recipes for automatic stock deduction',
    howRecipesWork: 'How Recipes Work',
    recipeDescription: 'Each product needs a recipe that lists all ingredients and quantities. When a product is sold, the system automatically deducts the required ingredients from stock.',
    setupRecipe: 'Setup Recipe',
    viewRecipe: 'View Recipe',
    calculateCost: 'Calculate Cost',
    ingredientsNeeded: 'Ingredients Needed',
    totalIngredientCost: 'Total Ingredient Cost',
    profitSummary: 'Profit Summary',
    sellingPrice: 'Selling Price',
    ingredientCost: 'Ingredient Cost',
    recipeExists: 'Recipe configured',
    noRecipe: 'No recipe configured',
    failedToLoadRecipe: 'Failed to load recipe',
    pleaseSelectIngredientAndQuantity: 'Please select an ingredient and enter quantity',
    pleaseAddAtLeastOneIngredient: 'Please add at least one ingredient',
    recipeSavedSuccessfully: 'Recipe saved successfully!',
    failedToSaveRecipe: 'Failed to save recipe',
    noRecipeFoundForProduct: 'No recipe found for this product',
    uncategorized: 'Uncategorized',
    recipe: 'Recipe',
    noIngredientsAddedYet: 'No ingredients added yet',
    selectIngredient: 'Select Ingredient',
    quantityRequired: 'Quantity Required',
    saveRecipe: 'Save Recipe',
    
    // -------------------- SETTINGS / RECEIPT --------------------
    receiptFooter: 'Receipt Footer Message',
    restaurantName: 'Restaurant Name',
    address: 'Address',
    workingHours: 'Working Hours',
    taxRate: 'Tax Rate',
    configureRestaurantPreferences: 'Configure your restaurant preferences',
    settingsSavedSuccessfully: 'Settings saved successfully!',
    restaurantInformation: 'Restaurant Information',
    businessSettings: 'Business Settings',
    receiptSettings: 'Receipt Settings',
    thankYouForDining: 'Thank you for dining with us!',
    saveSettings: 'Save Settings',
    settingsSaveInfo: 'Settings are saved to your browser. In a production environment, these would be saved to the database.',
    
    // -------------------- REAL-TIME NOTIFICATIONS --------------------
    lowStockAlert: 'Low Stock Alert',
    newOrderAlert: 'New Order Alert',
    orderReadyAlert: 'Order Ready Alert',
    salesReportReady: 'Sales Report Ready',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    
    // -------------------- CANCEL / VOID ORDER --------------------
    cancelOrderTitle: 'Cancel Order',
    voidOrderTitle: 'Void Order',
    cancellationReasonPlaceholder: 'Why is this order being cancelled?',
    voidReasonPlaceholder: 'Why is this order being voided?',
    voidDescription: 'Void means this order will be completely removed from sales records and stock will be restored. Use for test orders or system errors.',
    customerChangedMind: 'Customer changed mind',
    customerLeft: 'Customer left restaurant',
    orderTooLong: 'Order took too long',
    wrongItems: 'Wrong items ordered',
    duplicateOrder: 'Duplicate order',
    paymentIssue: 'Payment issue',
    kitchenCannotPrepare: 'Kitchen cannot prepare',
    systemError: 'System error - double charge',
    trainingError: 'Staff training error',
    testOrder: 'Test order',
    wrongTable: 'Wrong table charged',
    overcharged: 'Customer overcharged',
    
    // -------------------- ORDERS --------------------
    orders: 'Orders',
    orderDetails: 'Order Details',
    orderType: 'Order Type',
    dineIn: 'Dine In',
    takeaway: 'Takeaway',
    delivery: 'Delivery',
    orderStatus: 'Order Status',
    paymentStatus: 'Payment Status',
    paid: 'Paid',
    unpaid: 'Unpaid',
    pendingPayment: 'Pending Payment',
    itemsCount: 'Items Count',
    cancellationReason: 'Cancellation Reason',
    cancellationPlaceholder: 'e.g., Customer changed mind',
    yesCancel: 'Yes, Cancel',
    noKeep: 'No, Keep',
    noActiveOrder: 'No active order found. Please create a new order.',
    couldNotFetchOrder: 'Could not fetch active order',
    pleaseAddItems: 'Please add items to order',
    itemsAdded: 'Items added to order',
    failedToAddItems: 'Failed to add items',
    addItemsToOrder: 'Add Items to Order',
    currentTotal: 'Current Total',
    newTotal: 'New Total',
    addedSuccessfully: 'Items added successfully',
    
    // -------------------- DASHBOARD --------------------
    businessPerformance: 'Business performance overview',
    todayRevenue: "Today's Revenue",
    todayProfit: "Today's Profit",
    monthRevenue: 'Month Revenue',
    monthProfit: 'Month Profit',
    netProfit: 'Net Profit',
    weeklyTrend: 'Weekly Trend',
    monthlyTrend: 'Monthly Trend',
    yearlyTrend: 'Yearly Trend',
    topSellingProducts: 'Top Selling Products',
    recentSales: 'Recent Sales',
    paymentMethods: 'Payment Methods',
    hourlySales: 'Hourly Sales',
    dailyOrders: 'Daily Orders',
    totalProducts: 'Total Products',
    needReorder: 'Need reorder',
    critical: 'Critical',
    latestTransactions: 'Latest transactions',
    cashier: 'Cashier',
    system: 'System',
    noSalesYet: 'No sales yet',
    weekRevenue: 'Week Revenue',
    gross: 'Gross',
    netProfitMargin: 'Net Profit Margin',
    quickSummary: 'Quick Summary',
    avgOrderValue: 'Avg Order Value',
    ownerDashboard: 'Owner Dashboard',
    fullBusinessAnalytics: 'Full business analytics and control',
    totalStaff: 'Total Staff',
    activeEmployees: 'Active employees',
    totalOrders: 'Total Orders',
    monthNetProfit: 'Month Net Profit',
    
    // -------------------- MANAGER DASHBOARD --------------------
    managerDashboard: 'Manager Dashboard',
    operationalOverview: 'Operational overview',
    todaySales: "Today's Sales",
    staffOnDuty: 'Staff on Duty',
    ingredientsNeedReorder: 'ingredients need reordering',
    updateInventory: 'Update Inventory',
    addOrEditStockLevels: 'Add or edit stock levels',
    viewReports: 'View Reports',
    salesAndProfitAnalytics: 'Sales and profit analytics',
    paymentSuccessful: 'Payment successful!',
    completed: 'completed',
    paymentFailed: 'Payment failed',
    noOrdersReady: 'No orders ready for payment',
    ordersFromKitchenWillAppear: 'Orders from kitchen will appear here',
    customer: 'Customer',
    walkIn: 'Walk-in',
    readySince: 'Ready since',
    payment: 'Payment',
    order: 'Order',
    orderTotal: 'Order Total',
    complete: 'Complete',
    failedToUpdateOrderStatus: 'Failed to update order status',
    noOrdersToDisplay: 'No orders to display',
    ordersWillAppearHere: 'Orders will appear here when created',
    more: 'more',
    unavailable: 'Unavailable',
    addNew: 'Add New',
    selectUnit: 'Select unit',
    kilogram: 'Kilogram (kg)',
    gram: 'Gram (g)',
    liter: 'Liter (L)',
    milliliter: 'Milliliter (ml)',
    pieces: 'Pieces (pcs)',
    egVegetables: 'e.g., Vegetables',
    noIngredientsFound: 'No ingredients found',
    noProductsFound: 'No products found',
    deleteFailed: 'Failed to delete',
    ingredientsBelowMinStock: 'ingredients are below minimum stock level',
    
    // -------------------- ERROR MESSAGES --------------------
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid email or password',
    accountPending: 'Account pending approval. Please wait.',
    accountDeactivated: 'Account deactivated. Contact admin.',
    networkError: 'Network error. Please check your connection.',
    saveSuccess: 'Saved successfully',
    saveFailed: 'Failed to save',
    deleteConfirm: 'Are you sure you want to delete this?',
    cancelConfirm: 'Are you sure you want to cancel?',
    requiredField: 'This field is required',
    passwordMinLength: 'Password must be at least 6 characters',
    emailInvalid: 'Please enter a valid email address',
    stockInsufficient: 'Insufficient stock',
    
    // -------------------- BUTTONS --------------------
    submit: 'Submit',
    update: 'Update',
    create: 'Create',
    close: 'Close',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    
    // -------------------- TIME PERIODS --------------------
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last365Days: 'Last 365 Days',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    
    // -------------------- WEEK DAYS --------------------
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    
    // -------------------- MONTHS --------------------
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    
    // -------------------- AUTHENTICATION / LOGIN --------------------
    restaurantManagementSystem: 'Restaurant Management System',
    emailAddress: 'Email Address',
    loggingIn: 'Logging in...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    demoAccounts: 'Demo Accounts',
    createAccount: 'Create your account',
    fullNamePlaceholder: 'John Doe',
    passwordMinLengthPlaceholder: 'Min 6 characters',
    passwordMinLengthHint: 'Minimum 6 characters',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    accountCreated: 'Account Created!',
    accountPendingApproval: 'Your account has been created and is pending admin approval. You will be notified once approved.',
    goToLogin: 'Go to Login',
    signupFailed: 'Signup failed',
    emailPasswordRequired: 'Email and password are required',
    
    // -------------------- SALES --------------------
    sales: 'Sales',
    avgOrder: 'Avg Order',
    only: 'Only',
newOrdersWaiting: 'new orders waiting for kitchen',
isNow: 'is now',
qrCodeAvailable: 'QR Code available',
getQRCode: 'Get QR Code',
qrCodeForTable: 'QR Code for Table',
customersScanToOrder: 'Customers scan to view menu and order',
qrCodeInstructions: 'Share this link with customers. They can scan the QR code to view the menu and place orders from their phone.',
qrUrl: 'QR URL',
copyQrUrl: 'Copy QR URL',
qrNote: 'You can generate a physical QR code using any QR code generator website by pasting this URL.',
customers: 'Customers',
printQRCodes: 'Print QR Codes',
generateAndPrintQRCodes: 'Generate and print QR codes for all tables',
printAll: 'Print All',
copyUrl: 'Copy URL',
download: 'Download',
qrPrintInstructions: 'Print this page and cut out each QR code. Place them on corresponding tables. Customers can scan to view menu and order.',
pendingConfirmations: 'Confirm Orders',

  },
  
  // ============================================================
  // AMHARIC TRANSLATIONS (አማርኛ)
  // ============================================================
  am: {
    // -------------------- COMMON UI ELEMENTS --------------------
    dashboard: 'ዳሽቦርድ',
    logout: 'ውጣ',
    welcome: 'እንኳን ደህና መጡ',
    readyToServe: 'ደንበኞችን ለማገልገል ዝግጁ',
    search: 'ፈልግ...',
    notifications: 'ማሳወቂያዎች',
    settings: 'ቅንብሮች',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    delete: 'አጥፋ',
    edit: 'አርትዕ',
    refresh: 'አድስ',
    approve: 'ቀበል',
    reject: 'ውድቅ አድርግ',
    back: 'ተመለስ',
    confirm: 'አረጋግጥ',
    loading: 'በመጫን ላይ...',
    noData: 'ምንም ውሂብ የለም',
    actions: 'ድርጊቶች',
    status: 'ሁኔታ',
    date: 'ቀን',
    time: 'ሰዓት',
    total: 'ጠቅላላ',
    amount: 'መጠን',
    description: 'መግለጫ',
    name: 'ስም',
    email: 'ኢሜይል',
    phone: 'ስልክ',
    password: 'ይለፍ ቃል',
    role: 'ሚና',
    loggedInAs: 'ተጠቃሚ',
    
    // -------------------- USER ROLES --------------------
    owner: 'ባለቤት',
    manager: 'ሥራ አስኪያጅ',
    cashier: 'ገንዘብ ተቀባይ',
    waiter: 'አስተናጋጅ',
    kitchen: 'ኩሽና',
    admin: 'አስተዳዳሪ',
    staff: 'ሰራተኛ',
    
    // -------------------- POS / CASHIER MODULE --------------------
    posTerminal: 'የሽያጭ ተርሚናል',
    currentOrder: 'አሁን ያለው ትዕዛዝ',
    cartEmpty: 'ጋሪ ባዶ ነው',
    checkout: 'ክፈል',
    subtotal: 'ንዑስ ድምር',
    vat: 'ቫት (15%)',
    tax: 'ግብር',
    paymentMethod: 'የክፍያ ዘዴ',
    cash: 'ጥሬ ገንዘብ',
    card: 'ካርድ',
    mobile: 'ሞባይል',
    completeOrder: 'ትዕዛዝ ይጠናቀቅ',
    processPayment: 'ክፍያ አካሂድ',
    customerName: 'የደንበኛ ስም',
    customerPhone: 'የደንበኛ ስልክ',
    addToCart: 'ወደ ጋሪ ጨምር',
    quantity: 'ብዛት',
    items: 'እቃዎች',
    salesHistory: 'የሽያጭ ታሪክ',
    readyForPayment: 'ለክፍያ ዝግጁ',
    addToOrder: '+ ወደ ትዕዛዝ ጨምር',
    tapToAdd: 'ለመጨመር በምናሌ እቃዎች ላይ ይንኩ',
    
    // -------------------- KITCHEN MODULE --------------------
    kitchenDashboard: 'ኩሽና ዳሽቦርድ',
    manageFoodPreparation: 'ምግብ ዝግጅት ያስተዳድሩ',
    pending: 'በመጠባበቅ ላይ',
    preparing: 'በማዘጋጀት ላይ',
    ready: 'ዝግጁ',
    completed: 'ተጠናቅቋል',
    cancelled: 'ተሰርዟል',
    startCooking: 'ማብሰል ጀምር',
    markReady: 'ዝግጁ ምልክት አድርግ',
    readyForPickup: 'ለማንሳት ዝግጁ',
    newOrderReceived: 'አዲስ ትዕዛዝ ደርሷል',
    cooking: 'በማብሰል ላይ',
    ordersToPrepare: 'ለማዘጋጀት ያሉ ትዕዛዞች',
    
    // -------------------- WAITER / TABLE MANAGEMENT --------------------
    tableManagement: 'ጠረጴዛ አያያዝ',
    selectTable: 'ትዕዛዝ ለመጀመር ጠረጴዛ ምረጥ',
    floorPlan: 'የሬስቶራንቱ ወለል እቅድ',
    available: 'ክፍት',
    occupied: 'ተይዟል',
    reserved: 'የተያዘ',
    cleaning: 'በማጽዳት ላይ',
    capacity: 'አቅም',
    table: 'ጠረጴዛ',
    orderForTable: 'የጠረጴዛ ትዕዛዝ',
    specialInstructions: 'ልዩ መመሪያ',
    sendToKitchen: 'ወደ ኩሽና ላክ',
    activeOrders: 'ንቁ ትዕዛዞች',
    yourActiveOrders: 'የእርስዎ ንቁ ትዕዛዞች',
    orderNumber: 'የትዕዛዝ ቁጥር',
    cancelOrder: 'ትዕዛዝ ሰርዝ',
    addMoreItems: 'ተጨማሪ እቃዎች ጨምር',
    addItems: 'እቃዎች ጨምር',
    activeOrdersHidden: 'የተደበቁ ትዕዛዞች',
    showOrders: 'ትዕዛዞችን አሳይ',
    noActiveOrdersMessage: 'ምንም ንቁ ትዕዛዞች የሉም',
    myOrders: 'የኔ ትዕዛዞች',
    manageTables: 'የሬስቶራንት ጠረጴዛዎችን እና ትዕዛዞችን ያስተዳድሩ',
    hide: 'ደብቅ',
    clickToCreateOrder: 'ትዕዛዝ ለመፍጠር ጠቅ ያድርጉ',
    clickToAddItems: 'እቃዎች ለመጨመር ጠቅ ያድርጉ',
    newOrderForTable: 'አዲስ ትዕዛዝ ለጠረጴዛ',
    seats: 'መቀመጫዎች',
    searchMenu: 'ምናሌ ፈልግ...',
    allItems: 'ሁሉም እቃዎች',
    sending: 'በመላክ ላይ...',
    itemsToAdd: 'ለመጨመር ያሉ እቃዎች',
    noItemsSelected: 'ምንም እቃዎች አልተመረጡም',
    adding: 'በመጨመር ላይ...',
    isReserved: 'ተይዟል',
    isCleaning: 'በማጽዳት ላይ ነው',
    orderSent: 'ትዕዛዝ ወደ ኩሽና ተልኳል',
    failedToSubmitOrder: 'ትዕዛዝ ማስገባት አልተሳካም',
    orderCancelledSuccess: 'ትዕዛዝ በተሳካ ሁኔታ ተሰርዟል!',
    failedToCancelOrder: 'ትዕዛዝ መሰረዝ አልተሳካም',
    
    // -------------------- INVENTORY MANAGEMENT --------------------
    inventoryManagement: 'እቃዎች አያያዝ',
    manageProductsAndIngredients: 'ምርቶችን እና ንጥረ ነገሮችን ያስተዳድሩ',
    ingredients: 'ንጥረ ነገሮች',
    products: 'ምርቶች',
    addIngredient: 'ንጥረ ነገር ጨምር',
    addProduct: 'ምርት ጨምር',
    stock: 'ክምችት',
    minStock: 'ዝቅተኛ ክምችት',
    unit: 'ክፍል',
    unitCost: 'የአንድ ክፍል ዋጋ',
    category: 'ምድብ',
    supplier: 'አቅራቢ',
    lowStock: 'ዝቅተኛ ክምችት',
    outOfStock: 'ክምችት የለም',
    inStock: 'ክምችት አለ',
    adjustStock: 'ክምችት አስተካክል',
    currentStock: 'የአሁኑ ክምችት',
    lowStockDescription: 'የሚከተሉት ንጥረ ነገሮች ከዝቅተኛ ክምችት በታች ናቸው:',
    left: 'ቀርቷል',
    min: 'ዝቅተኛ',
    moreItems: 'ተጨማሪ እቃዎች',
    noIngredientsFound: 'ምንም ንጥረ ነገሮች አልተገኙም',
    noProductsFound: 'ምንም ምርቶች አልተገኙም',
    deleteFailed: 'መሰረዝ አልተሳካም',
    ingredientsBelowMinStock: 'ንጥረ ነገሮች ከዝቅተኛ ክምችት በታች ናቸው',
    addNew: 'አዲስ ጨምር',
    selectUnit: 'ክፍል ምረጥ',
    kilogram: 'ኪሎ ግራም',
    gram: 'ግራም',
    liter: 'ሊትር',
    milliliter: 'ሚሊሊትር',
    pieces: 'ቁራጮች',
    egVegetables: 'ለምሳሌ: አትክልቶች',
    
    // -------------------- EXPENSE TRACKING --------------------
    expenseTracking: 'ወጪ ክትትል',
    trackBusinessOperationalCosts: 'የንግድ ሥራ ወጪዎችን ይከታተሉ',
    addExpense: 'ወጪ ጨምር',
    expenses: 'ወጪዎች',
    expenseCategory: 'የወጪ ምድብ',
    rent: 'ኪራይ',
    utilities: 'መገልገያዎች',
    salaries: 'ደሞዝ',
    marketing: 'ግብይት',
    maintenance: 'ጥገና',
    supplies: 'ቁሳቁሶች',
    transport: 'ትራንስፖርት',
    insurance: 'ኢንሹራንስ',
    taxes: 'ግብሮች',
    other: 'ሌላ',
    recordedBy: 'የተመዘገበው በ',
    expenseDate: 'የወጪ ቀን',
    thisMonth: 'በዚህ ወር',
    thisYear: 'በዚህ ዓመት',
    from: 'ከ',
    to: 'እስከ',
    totalExpenses: 'ጠቅላላ ወጪዎች',
    averageDaily: 'አማካይ ዕለታዊ',
    perDay: 'በቀን',
    categories: 'ምድቦች',
    differentExpenseTypes: 'የተለያዩ የወጪ አይነቶች',
    expenseByCategory: 'ወጪ በምድብ',
    transactions: 'ግብይቶች',
    searchExpenses: 'ወጪዎችን ፈልግ...',
    noExpensesFound: 'ምንም ወጪዎች አልተገኙም',
    editExpense: 'ወጪ አርትዕ',
    selectCategory: 'ምድብ ምረጥ',
    optionalDescription: 'አማራጭ መግለጫ...',
    
    // -------------------- PROFIT REPORTS --------------------
    profitReports: 'ትርፍ ሪፖርቶች',
    trackYourBusinessProfitability: 'የንግድ ትርፋማነትዎን ይከታተሉ',
    totalRevenue: 'ጠቅላላ ገቢ',
    totalCost: 'ጠቅላላ ወጪ',
    totalProfit: 'ጠቅላላ ትርፍ',
    profitMargin: 'የትርፍ ህዳግ',
    dailyBreakdown: 'ዕለታዊ ክፍፍል',
    topProducts: 'ከፍተኛ ምርቶች',
    byProfitContribution: 'በትርፍ አስተዋጽኦ',
    sold: 'ተሽጧል',
    revenue: 'ገቢ',
    cost: 'ወጪ',
    profit: 'ትርፍ',
    margin: 'ህዳግ',
    averageOrder: 'አማካይ ትዕዛዝ',
    todayPerformance: 'የዛሬ አፈጻጸም',
    revenueProfitTrend: 'የገቢ እና ትርፍ አዝማሚያ',
    hourlySalesTrend: 'የሰዓት ሽያጭ አዝማሚያ',
    hour: 'ሰዓት',
    product: 'ምርት',
    report: 'ሪፖርት',
    generated: 'የተፈጠረ',
    exportFailed: 'መላክ አልተሳካም',
    pdfExportError: 'የPDF መላክ ስህተት',
    exportExcel: 'Excel ላክ',
    exportPDF: 'PDF ላክ',
    noDataToExport: 'ለመላክ ምንም ውሂብ የለም',
    salesReports: 'የሽያጭ ሪፖርቶች',
    profit: 'ትርፍ',
    performanceByDay: 'አፈጻጸም በቀን',
    noSalesDataForPeriod: 'ለተመረጠው ጊዜ ምንም የሽያጭ ውሂብ የለም',
    
    // -------------------- STAFF MANAGEMENT --------------------
    staffManagement: 'ሰራተኞች አያያዝ',
    manageStaffAccountsAndPermissions: 'የሰራተኛ መለያዎችን እና ፈቃዶችን ያስተዳድሩ',
    addStaff: 'ሰራተኛ ጨምር',
    editStaff: 'ሰራተኛ አርትዕ',
    deleteStaff: 'ሰራተኛ አጥፋ',
    fullName: 'ሙሉ ስም',
    joinDate: 'የተቀላቀሉበት ቀን',
    lastLogin: 'የመጨረሻ ግቤት',
    pendingApproval: 'በመጠባበቅ ላይ',
    active: 'ንቁ',
    inactive: 'ንቁ ያልሆነ',
    pendingApprovals: 'በመጠባበቅ ላይ ያሉ',
    reviewAndApproveStaffAccounts: 'አዲስ የሰራተኛ መለያ ጥያቄዎችን ይገምግሙ እና ያጽድቁ',
    defaultRole: 'ነባር ሚና',
    userApproved: 'ተጠቃሚ በተሳካ ሁኔታ ጸድቋል',
    userRejected: 'ተጠቃሚ ውድቅ ተደርጓል',
    waitingForApproval: 'የአስተዳዳሪ ማጽደቅ በመጠባበቅ ላይ',
    staffPerformance: 'የሰራተኛ አፈጻጸም',
    salesPerformance: 'የሽያጭ አፈጻጸም',
    moreStaff: 'ተጨማሪ ሰራተኞች',
    noSalesData: 'ለዚህ ጊዜ ምንም የሽያጭ ውሂብ የለም',
    topPerformer: '🏆 ከፍተኛ አፈጻጸም',
    noStaffMembersFound: 'ምንም ሰራተኞች አልተገኙም',
    accessDeniedOnlyOwners: 'መድረስ አልተፈቀደም። ባለቤቶች እና አስተዳዳሪዎች ብቻ ሰራተኞችን ማየት ይችላሉ።',
    failedToLoadStaff: 'ሰራተኞችን መጫን አልተሳካም',
    staffUpdatedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ዘምኗል!',
    staffCreatedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ተፈጥሯል! የአስተዳዳሪ ማጽደቅ ያስፈልጋቸዋል።',
    failedToSaveStaff: 'ሰራተኛ ማስቀመጥ አልተሳካም',
    deleteStaffConfirm: 'ይህን ሰራተኛ መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት? ይህ ድርጊት ሊቀለበስ አይችልም።',
    staffDeletedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ተሰርዟል!',
    failedToDeleteStaff: 'ሰራተኛ መሰረዝ አልተሳካም',
    roles: 'ሚናዎች',
    clickAddStaffToCreate: 'አዲስ መለያ ለመፍጠር "ሰራተኛ ጨምር" ን ጠቅ ያድርጉ',
    editStaffMember: 'ሰራተኛ አርትዕ',
    addNewStaffMember: 'አዲስ ሰራተኛ ጨምር',
    enterFullName: 'ሙሉ ስም ያስገቡ',
    enterEmailAddress: 'ኢሜይል አድራሻ ያስገቡ',
    minimum6Characters: 'ቢያንስ 6 ቁምፊዎች',
    fullAccess: 'ሙሉ መድረሻ',
    operationalAccess: 'የሥራ ክወና መድረሻ',
    paymentOnly: 'ክፍያ ብቻ',
    orderTaking: 'ትዕዛዝ መውሰድ',
    foodPrepOnly: 'ምግብ ዝግጅት ብቻ',
    phoneNumber: 'ስልክ ቁጥር',
    optional: 'አማራጭ',
    updateStaff: 'ሰራተኛ አዘምን',
    createStaff: 'ሰራተኛ ፍጠር',
    accessDeniedOnlyOwnersAndAdmins: 'መድረስ አልተፈቀደም። ባለቤቶች እና አስተዳዳሪዎች ብቻ በመጠባበቅ ላይ ያሉ ማጽደቆችን ማየት ይችላሉ።',
    failedToLoadPendingUsers: 'በመጠባበቅ ላይ ያሉ ተጠቃሚዎችን መጫን አልተሳካም',
    userApprovedSuccessfully: 'ተጠቃሚ በተሳካ ሁኔታ ጸድቋል! አሁን መግባት ይችላሉ።',
    failedToApproveUser: 'ተጠቃሚን ማጽደቅ አልተሳካም',
    rejectUserConfirm: 'ይህን ተጠቃሚ ውድቅ ማድረግ እንደሚፈልጉ እርግጠኛ ነዎት? ከስርዓቱ ይወገዳሉ።',
    userRejectedAndRemoved: 'ተጠቃሚ ውድቅ ተደርጓል እና ተወግዷል።',
    failedToRejectUser: 'ተጠቃሚን ውድቅ ማድረግ አልተሳካም',
    usersWaiting: 'ተጠቃሚዎች በመጠባበቅ ላይ',
    noPendingApprovals: 'ምንም በመጠባበቅ ላይ ያሉ ማጽደቆች የሉም',
    allStaffAccountsApproved: 'ሁሉም የሰራተኛ መለያዎች ጸድቀዋል',
    newStaffWillAppearHere: 'አዲስ ሰራተኞች ሲመዘገቡ እዚህ ይታያሉ',
    notProvided: 'አልቀረበም',
    requested: 'የተጠየቀ',
    assignRole: 'ሚና መድብ',
    basicAccess: 'መሰረታዊ መድረሻ',
    operations: 'ስራዎች',
    tipApprovedUsersWillReceiveEmail: 'የጸደቁ ተጠቃሚዎች የኢሜይል ማሳወቂያ ይቀበላሉ እና ወዲያውኑ በምስክር ወረቀታቸው መግባት ይችላሉ።',
    
    // -------------------- RECIPE MANAGEMENT --------------------
    recipeManagement: 'የምግብ አዘገጃጀት አያያዝ',
    defineProductRecipes: 'ለራስ-ሰር ክምችት መቀነስ የምርት አዘገጃጀቶችን ይግለጹ',
    howRecipesWork: 'የምግብ አዘገጃጀቶች አሠራር',
    recipeDescription: 'እያንዳንዱ ምርት ሁሉንም ንጥረ ነገሮች እና መጠኖች የሚዘረዝር የምግብ አዘገጃጀት ያስፈልገዋል። አንድ ምርት ሲሸጥ ስርዓቱ አስፈላጊዎቹን ንጥረ ነገሮች ከክምችት በራስ-ሰር ይቀንሳል።',
    setupRecipe: 'የምግብ አዘገጃጀት አዘጋጅ',
    viewRecipe: 'የምግብ አዘገጃጀት ተመልከት',
    calculateCost: 'ወጪ አስላ',
    ingredientsNeeded: 'የሚፈለጉ ንጥረ ነገሮች',
    totalIngredientCost: 'ጠቅላላ የንጥረ ነገር ዋጋ',
    profitSummary: 'የትርፍ ማጠቃለያ',
    sellingPrice: 'የሽያጭ ዋጋ',
    ingredientCost: 'የንጥረ ነገር ዋጋ',
    recipeExists: 'የምግብ አዘገጃጀት ተዘጋጅቷል',
    noRecipe: 'ምንም የምግብ አዘገጃጀት አልተዘጋጀም',
    failedToLoadRecipe: 'የምግብ አዘገጃጀት መጫን አልተሳካም',
    pleaseSelectIngredientAndQuantity: 'እባክዎ ንጥረ ነገር ይምረጡ እና መጠን ያስገቡ',
    pleaseAddAtLeastOneIngredient: 'እባክዎ ቢያንስ አንድ ንጥረ ነገር ይጨምሩ',
    recipeSavedSuccessfully: 'የምግብ አዘገጃጀት በተሳካ ሁኔታ ተቀምጧል!',
    failedToSaveRecipe: 'የምግብ አዘገጃጀት ማስቀመጥ አልተሳካም',
    noRecipeFoundForProduct: 'ለዚህ ምርት ምንም የምግብ አዘገጃጀት አልተገኘም',
    uncategorized: 'ምድብ አልተመደበም',
    recipe: 'የምግብ አዘገጃጀት',
    noIngredientsAddedYet: 'እስካሁን ምንም ንጥረ ነገሮች አልተጨመሩም',
    selectIngredient: 'ንጥረ ነገር ምረጥ',
    quantityRequired: 'የሚፈለገው መጠን',
    saveRecipe: 'የምግብ አዘገጃጀት አስቀምጥ',
    
    // -------------------- SETTINGS / RECEIPT --------------------
    receiptFooter: 'የደረሰኝ ግርጌ መልዕክት',
    restaurantName: 'የሬስቶራንት ስም',
    address: 'አድራሻ',
    workingHours: 'የስራ ሰዓታት',
    taxRate: 'የግብር መጠን',
    configureRestaurantPreferences: 'የሬስቶራንት ምርጫዎችዎን ያዋቅሩ',
    settingsSavedSuccessfully: 'ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል!',
    restaurantInformation: 'የሬስቶራንት መረጃ',
    businessSettings: 'የንግድ ቅንብሮች',
    receiptSettings: 'የደረሰኝ ቅንብሮች',
    thankYouForDining: 'እንደመገብዎ እናመሰግናለን!',
    saveSettings: 'ቅንብሮችን አስቀምጥ',
    settingsSaveInfo: 'ቅንብሮች በአሳሽዎ ውስጥ ተቀምጠዋል። በምርት አካባቢ ውስጥ እነዚህ በውሂብ ጎታ ውስጥ ይቀመጣሉ።',
    
    // -------------------- REAL-TIME NOTIFICATIONS --------------------
    lowStockAlert: 'ዝቅተኛ ክምችት ማስጠንቀቂያ',
    newOrderAlert: 'አዲስ ትዕዛዝ ማስጠንቀቂያ',
    orderReadyAlert: 'የትዕዛዝ ዝግጅት ማስጠንቀቂያ',
    salesReportReady: 'የሽያጭ ሪፖርት ዝግጁ',
    markAllRead: 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    noNotifications: 'ምንም ማሳወቂያዎች የሉም',
    
    // -------------------- CANCEL / VOID ORDER --------------------
    cancelOrderTitle: 'ትዕዛዝ ሰርዝ',
    voidOrderTitle: 'ትዕዛዝ ባዶ አድርግ',
    cancellationReasonPlaceholder: 'ይህ ትዕዛዝ የተሰረዘው ለምንድነው?',
    voidReasonPlaceholder: 'ይህ ትዕዛዝ የተባዶው ለምንድነው?',
    voidDescription: 'ባዶ ማለት ይህ ትዕዛዝ ከሽያጭ መዝገቦች ሙሉ በሙሉ ይወገዳል እና ክምችት ወደ ቀድሞው ይመለሳል ማለት ነው። ለሙከራ ትዕዛዞች ወይም የስርዓት ስህተቶች ይጠቀሙ።',
    customerChangedMind: 'ደንበኛ ሀሳቡን ቀይሯል',
    customerLeft: 'ደንበኛ ሬስቶራንቱን ለቆ ወጥቷል',
    orderTooLong: 'ትዕዛዙ ብዙ ጊዜ ወስዷል',
    wrongItems: 'የተሳሳቱ እቃዎች ታዝዘዋል',
    duplicateOrder: 'የተደገመ ትዕዛዝ',
    paymentIssue: 'የክፍያ ችግር',
    kitchenCannotPrepare: 'ኩሽና ማዘጋጀት አይችልም',
    systemError: 'የስርዓት ስህተት - ድርብ ክፍያ',
    trainingError: 'የሰራተኛ ስልጠና ስህተት',
    testOrder: 'የሙከራ ትዕዛዝ',
    wrongTable: 'የተሳሳተ ጠረጴዛ ተከፍሏል',
    overcharged: 'ደንበኛ ከመጠን በላይ ተከፍሏል',
    
    // -------------------- ORDERS --------------------
    orders: 'ትዕዛዞች',
    orderDetails: 'የትዕዛዝ ዝርዝሮች',
    orderType: 'የትዕዛዝ አይነት',
    dineIn: 'እዚህ በልታ',
    takeaway: 'ለማስወጣት',
    delivery: 'ማድረስ',
    orderStatus: 'የትዕዛዝ ሁኔታ',
    paymentStatus: 'የክፍያ ሁኔታ',
    paid: 'ተከፍሏል',
    unpaid: 'አልተከፈለም',
    pendingPayment: 'ክፍያ በመጠባበቅ ላይ',
    itemsCount: 'የእቃዎች ብዛት',
    cancellationReason: 'የመሰረዝ ምክንያት',
    cancellationPlaceholder: 'ለምሳሌ: ደንበኛ ሀሳቡን ቀይሯል',
    yesCancel: 'አዎ፣ ሰርዝ',
    noKeep: 'አይ፣ አትሰርዝ',
    noActiveOrder: 'ምንም ንቁ ትዕዛዝ አልተገኘም። እባክዎ አዲስ ትዕዛዝ ይፍጠሩ።',
    couldNotFetchOrder: 'ንቁ ትዕዛዝ ማግኘት አልተቻለም',
    pleaseAddItems: 'እባክዎ እቃዎችን ወደ ትዕዛዝ ይጨምሩ',
    itemsAdded: 'እቃዎች ወደ ትዕዛዝ ተጨምረዋል',
    failedToAddItems: 'እቃዎችን መጨመር አልተሳካም',
    addItemsToOrder: 'ወደ ትዕዛዝ እቃዎች ጨምር',
    currentTotal: 'አሁን ያለው ጠቅላላ',
    newTotal: 'አዲስ ጠቅላላ',
    addedSuccessfully: 'እቃዎች በተሳካ ሁኔታ ተጨምረዋል',
    
    // -------------------- DASHBOARD --------------------
    businessPerformance: 'የንግድ አፈጻጸም አጠቃላይ እይታ',
    todayRevenue: 'የዛሬ ገቢ',
    todayProfit: 'የዛሬ ትርፍ',
    monthRevenue: 'የወር ገቢ',
    monthProfit: 'የወር ትርፍ',
    netProfit: 'የተጣራ ትርፍ',
    weeklyTrend: 'ሳምንታዊ አዝማሚያ',
    monthlyTrend: 'ወርሃዊ አዝማሚያ',
    yearlyTrend: 'ዓመታዊ አዝማሚያ',
    topSellingProducts: 'ከፍተኛ ሽያጭ ያላቸው ምርቶች',
    recentSales: 'የቅርብ ጊዜ ሽያጮች',
    paymentMethods: 'የክፍያ ዘዴዎች',
    hourlySales: 'የሰዓት ሽያጮች',
    dailyOrders: 'ዕለታዊ ትዕዛዞች',
    totalProducts: 'ጠቅላላ ምርቶች',
    needReorder: 'እንደገና ማዘዝ ያስፈልጋል',
    critical: 'ከፍተኛ',
    latestTransactions: 'የቅርብ ጊዜ ግብይቶች',
    cashier: 'ገንዘብ ተቀባይ',
    system: 'ሲስተም',
    noSalesYet: 'እስካሁን ሽያጭ የለም',
    weekRevenue: 'የሳምንት ገቢ',
    gross: 'ጠቅላላ',
    netProfitMargin: 'የተጣራ ትርፍ ህዳግ',
    quickSummary: 'ፈጣን ማጠቃለያ',
    avgOrderValue: 'አማካይ የትዕዛዝ ዋጋ',
    ownerDashboard: 'የባለቤት ዳሽቦርድ',
    fullBusinessAnalytics: 'ሙሉ የንግድ ትንታኔ እና ቁጥጥር',
    totalStaff: 'ጠቅላላ ሰራተኞች',
    activeEmployees: 'ንቁ ሰራተኞች',
    totalOrders: 'ጠቅላላ ትዕዛዞች',
    monthNetProfit: 'የወር የተጣራ ትርፍ',
    
    // -------------------- MANAGER DASHBOARD --------------------
    managerDashboard: 'የሥራ አስኪያጅ ዳሽቦርድ',
    operationalOverview: 'የሥራ አፈጻጸም አጠቃላይ እይታ',
    todaySales: 'የዛሬ ሽያጮች',
    staffOnDuty: 'በሥራ ላይ ያሉ ሰራተኞች',
    ingredientsNeedReorder: 'ንጥረ ነገሮች እንደገና ማዘዝ ያስፈልጋቸዋል',
    updateInventory: 'ክምችት አዘምን',
    addOrEditStockLevels: 'የክምችት ደረጃዎችን ጨምር ወይም አርትዕ',
    viewReports: 'ሪፖርቶችን ተመልከት',
    salesAndProfitAnalytics: 'የሽያጭ እና ትርፍ ትንታኔዎች',
    paymentSuccessful: 'ክፍያ ተሳክቷል!',
    completed: 'ተጠናቋል',
    paymentFailed: 'ክፍያ አልተሳካም',
    noOrdersReady: 'ለክፍያ ዝግጁ የሆኑ ትዕዛዞች የሉም',
    ordersFromKitchenWillAppear: 'ከኩሽና ትዕዛዞች እዚህ ይታያሉ',
    customer: 'ደንበኛ',
    walkIn: 'ያለቀጠሮ',
    readySince: 'ዝግጁ የሆነው ከ',
    payment: 'ክፍያ',
    order: 'ትዕዛዝ',
    orderTotal: 'ጠቅላላ ትዕዛዝ',
    complete: 'አጠናቅቅ',
    failedToUpdateOrderStatus: 'የትዕዛዝ ሁኔታ ማዘመን አልተሳካም',
    noOrdersToDisplay: 'ለማሳየት ምንም ትዕዛዞች የሉም',
    ordersWillAppearHere: 'ሲፈጠሩ ትዕዛዞች እዚህ ይታያሉ',
    more: 'ተጨማሪ',
    unavailable: 'አይገኝም',
    
    // -------------------- ERROR MESSAGES --------------------
    loginFailed: 'መግባት አልተሳካም',
    invalidCredentials: 'የተሳሳተ ኢሜይል ወይም ይለፍ ቃል',
    accountPending: 'መለያ በመጠባበቅ ላይ ነው። እባክዎ ይጠብቁ።',
    accountDeactivated: 'መለያ ተሰርዟል። አስተዳዳሪን ያነጋግሩ።',
    networkError: 'የአውታረ መረብ ስህተት። እባክዎ ግንኙነትዎን ያረጋግጡ።',
    saveSuccess: 'በተሳካ ሁኔታ ተቀምጧል',
    saveFailed: 'ማስቀመጥ አልተሳካም',
    deleteConfirm: 'ይህን መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    cancelConfirm: 'መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
    requiredField: 'ይህ መስክ ያስፈልጋል',
    passwordMinLength: 'ይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
    stockInsufficient: 'በቂ ያልሆነ ክምችት',
    
    // -------------------- BUTTONS --------------------
    submit: 'አስገባ',
    update: 'አዘምን',
    create: 'ፍጠር',
    close: 'ዝጋ',
    export: 'ላክ',
    import: 'አምጣ',
    print: 'አትም',
    download: 'አውርድ',
    upload: 'ጫን',
    
    // -------------------- TIME PERIODS --------------------
    last7Days: 'ባለፉት 7 ቀናት',
    last30Days: 'ባለፉት 30 ቀናት',
    last365Days: 'ባለፉት 365 ቀናት',
    week: 'ሳምንት',
    month: 'ወር',
    year: 'ዓመት',
    
    // -------------------- WEEK DAYS --------------------
    monday: 'ሰኞ',
    tuesday: 'ማክሰኞ',
    wednesday: 'ረቡዕ',
    thursday: 'ሐሙስ',
    friday: 'አርብ',
    saturday: 'ቅዳሜ',
    sunday: 'እሑድ',
    
    // -------------------- MONTHS --------------------
    january: 'ጥር',
    february: 'የካቲት',
    march: 'መጋቢት',
    april: 'ሚያዚያ',
    may: 'ግንቦት',
    june: 'ሰኔ',
    july: 'ሐምሌ',
    august: 'ነሐሴ',
    september: 'መስከረም',
    october: 'ጥቅምት',
    november: 'ህዳር',
    december: 'ታህሳስ',
    
    // -------------------- AUTHENTICATION / LOGIN --------------------
    restaurantManagementSystem: 'የሬስቶራንት አስተዳደር ሲስተም',
    emailAddress: 'ኢሜይል አድራሻ',
    loggingIn: 'በመግባት ላይ...',
    signIn: 'ግባ',
    noAccount: 'መለያ የለዎትም?',
    signUp: 'ተመዝገብ',
    demoAccounts: 'የሙከራ መለያዎች',
    createAccount: 'መለያ ይፍጠሩ',
    fullNamePlaceholder: 'ጆን ዶ',
    passwordMinLengthPlaceholder: 'ቢያንስ 6 ቁምፊዎች',
    passwordMinLengthHint: 'ቢያንስ 6 ቁምፊዎች',
    creatingAccount: 'መለያ በመፍጠር ላይ...',
    alreadyHaveAccount: 'አስቀድሞ መለያ አለዎት?',
    accountCreated: 'መለያ ተፈጥሯል!',
    accountPendingApproval: 'መለያዎ ተፈጥሯል እና በአስተዳዳሪ ማጽደቅ ላይ ነው። አንዴ ከጸደቀ ይነገሩዎታል።',
    goToLogin: 'ወደ መግቢያ ሂድ',
    signupFailed: 'ምዝገባ አልተሳካም',
    emailPasswordRequired: 'ኢሜይል እና ይለፍ ቃል ያስፈልጋሉ',
    
    // -------------------- SALES --------------------
    sales: 'ሽያጮች',
    avgOrder: 'አማካይ ትዕዛዝ',
    only: 'ብቻ',
newOrdersWaiting: 'አዲስ ትዕዛዞች ኩሽና በመጠባበቅ ላይ',
isNow: 'አሁን',
qrCodeAvailable: 'QR ኮድ ይገኛል',
getQRCode: 'QR ኮድ አግኝ',
qrCodeForTable: 'ለጠረጴዛ QR ኮድ',
customersScanToOrder: 'ደንበኞች ምናሌውን ለማየት እና ለማዘዝ ይህንን ይቃኙ',
qrCodeInstructions: 'ይህን አገናኝ ከደንበኞች ጋር ያጋሩ። ምናሌውን ለማየት እና ትዕዛዝ ለማስገባት የQR ኮድ መቃኘት ይችላሉ።',
qrUrl: 'QR አገናኝ',
copyQrUrl: 'QR አገናኝ ቅዳ',
qrNote: 'ይህን አገናኝ በመጠቀም በማንኛውም የQR ኮድ ማመንጫ ድህረ ገጽ አካላዊ QR ኮድ መፍጠር ይችላሉ።',
customers: 'ደንበኞች',
printQRCodes: 'QR ኮዶች አትም',
generateAndPrintQRCodes: 'ለሁሉም ጠረጴዛዎች QR ኮዶችን ፍጠር እና አትም',
printAll: 'ሁሉንም አትም',
copyUrl: 'አገናኝ ቅዳ',
download: 'አውርድ',
pendingConfirmations: 'ትዕዛዞችን አረጋግጥ',
qrPrintInstructions: 'ይህን ገጽ አትመው እያንዳንዱን QR ኮድ ይቁረጡ። በየጠረጴዛው ላይ ያድርጓቸው። ደንበኞች ምናሌውን ለማየት እና ለማዘዝ መቃኘት ይችላሉ።',
  }
};

// ============================================================
// LANGUAGE CONTEXT PROVIDER
// ============================================================
// This creates a React Context that makes the current language
// and translation function available to all components.
//
// Usage in components:
//   import { useLanguage } from '../context/LanguageContext';
//   const { t, language, setLanguage } = useLanguage();
//   <button onClick={() => setLanguage('am')}>አማርኛ</button>
//   <h1>{t('dashboard')}</h1>
// ============================================================

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  // Initialize language from localStorage or default to English
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  // Save language preference to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // Translation function - returns the translated text for a given key
  // Falls back to English if translation doesn't exist in current language
  const t = (key) => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};