import React, { createContext, useState, useContext, useEffect } from 'react';

/**
 * ============================================================
 * ETHIOPIAN RESTAURANT POS SYSTEM - LANGUAGE CONTEXT
 * ============================================================
 * 
 * This file contains ALL translations for the entire POS system.
 * 
 * Supported languages:
 *   - English (en) - Default
 *   - Amharic (am) - አማርኛ
 * 
 * ============================================================
 */

const translations = {
  // ==========================================================
  // ENGLISH TRANSLATIONS
  // ==========================================================
  en: {
    // ---------- COMMON UI ----------
    dashboard: 'Dashboard',
    logout: 'Logout',
    welcome: 'Welcome back',
    readyToServe: 'Ready to serve customers',
    search: 'Search...',
    notifications: 'Notifications',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    refresh: 'Refresh',
    approve: 'Approve',
    reject: 'Reject',
    back: 'Back',
    confirm: 'Confirm',
    loading: 'Loading...',
    noData: 'No data available',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    total: 'Total',
    amount: 'Amount',
    description: 'Description',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    password: 'Password',
    role: 'Role',
    loggedInAs: 'Logged in as',
    submit: 'Submit',
    update: 'Update',
    create: 'Create',
    close: 'Close',
    export: 'Export',
    import: 'Import',
    print: 'Print',
    download: 'Download',
    upload: 'Upload',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    order_taker: 'Order Taker',
    station: 'Station',
    addNew: 'Add New',
    safetyStock: 'Safety Stock',
    selectCategory: 'Select category',
    saveFailed: 'Failed to save',
    deleteFailed: 'Failed to delete',
    deleteConfirm: 'Are you sure you want to delete this?',
    ingredient: 'Ingredient',
    product: 'Product',
    currencySymbol: 'Br',
    currency: 'Birr',

    // ---------- USER ROLES ----------
    owner: 'Owner',
    manager: 'Manager',
    cashier: 'Cashier',
    waiter: 'Waiter',
    kitchen: 'Kitchen',
    admin: 'Admin',
    staff: 'Staff',

    // ---------- DARK MODE ----------
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    theme: 'Theme',

    // ---------- POS / CASHIER MODULE ----------
    posTerminal: 'POS Terminal',
    currentOrder: 'Current Order',
    cartEmpty: 'Cart is empty',
    checkout: 'Checkout',
    subtotal: 'Subtotal',
    vat: 'VAT (15%)',
    tax: 'Tax',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    mobile: 'Mobile',
    completeOrder: 'Complete Order',
    processPayment: 'Process Payment',
    customerName: 'Customer name',
    customerPhone: 'Customer phone',
    addToCart: 'Add to Cart',
    quantity: 'Quantity',
    items: 'Items',
    salesHistory: 'Sales History',
    readyForPayment: 'Ready for Payment',
    addToOrder: '+ Add to order',
    tapToAdd: 'Tap on menu items to add',
    manualOrder: 'Manual Order',
    walkInCustomer: 'Walk-in Customer',
    proceedToCheckout: 'Proceed to Checkout',
    clearCart: 'Clear Cart',
    orderSent: 'Order sent to kitchen',
    noOrdersReady: 'No orders ready for payment',
    ordersFromKitchenWillAppear: 'Orders from kitchen will appear here',
    payment: 'Payment',
    orderTotal: 'Order Total',
    complete: 'Complete',
    paymentSuccessful: 'Payment successful!',
    paymentFailed: 'Payment failed',
    ordersReady: 'Orders Ready',
    readySince: 'Ready since',
    customer: 'Customer',

    // ---------- KITCHEN MODULE ----------
    kitchenDashboard: 'Kitchen Dashboard',
    manageFoodPreparation: 'Manage food preparation',
    pending: 'Pending',
    preparing: 'Preparing',
    ready: 'Ready',
    completed: 'Completed',
    cancelled: 'Cancelled',
    startCooking: 'Start Cooking',
    markReady: 'Mark Ready',
    readyForPickup: 'Ready for Pickup',
    newOrderReceived: 'New order received',
    cooking: 'Cooking',
    ordersToPrepare: 'Orders to prepare',
    active: 'Active',
    noOrdersToDisplay: 'No orders to display',
    ordersWillAppearHere: 'Orders will appear here when created',
    kitchenStatus: 'Kitchen Status',
    waitingTime: 'Waiting Time',
    failedToUpdateOrderStatus: 'Failed to update order status',
    newOrdersWaiting: 'new orders waiting for kitchen',
    isNow: 'is now',
    order: 'Order',

    // ---------- WAITER / TABLE MANAGEMENT ----------
    tableManagement: 'Table Management',
    selectTable: 'Select a table to start an order',
    floorPlan: 'Restaurant Floor Plan',
    available: 'Available',
    occupied: 'Occupied',
    reserved: 'Reserved',
    cleaning: 'Cleaning',
    capacity: 'Cap',
    table: 'Table',
    orderForTable: 'Order for Table',
    specialInstructions: 'Special instructions',
    sendToKitchen: 'Send to Kitchen',
    activeOrders: 'Active Orders',
    yourActiveOrders: 'Your Active Orders',
    orderNumber: 'Order Number',
    cancelOrder: 'Cancel Order',
    addMoreItems: 'Add More Items',
    addItems: 'Add Items',
    activeOrdersHidden: 'Hidden Orders',
    showOrders: 'Show Orders',
    noActiveOrdersMessage: 'No active orders',
    myOrders: 'My Orders',
    manageTables: 'Manage your restaurant tables and orders',
    hide: 'Hide',
    clickToCreateOrder: 'Click to create order',
    clickToAddItems: 'Click to add items',
    newOrderForTable: 'New Order for Table',
    seats: 'seats',
    searchMenu: 'Search menu...',
    allItems: 'All Items',
    sending: 'Sending...',
    itemsToAdd: 'Items to Add',
    noItemsSelected: 'No items selected',
    adding: 'Adding...',
    isReserved: 'is reserved',
    isCleaning: 'is being cleaned',
    orderSentKitchen: 'Order sent to kitchen',
    failedToSubmitOrder: 'Failed to submit order',
    orderCancelledSuccess: 'Order cancelled successfully!',
    failedToCancelOrder: 'Failed to cancel order',
    pendingConfirmations: 'Confirm Orders',
    tableStatus: 'Table Status',
    manageTableAvailability: 'Manage table availability, reservations, and cleaning status',
    changeStatus: 'Change Status',
    yourAssignedTables: 'Your Assigned Tables',
    noTablesAssigned: 'No Tables Assigned',
    contactManager: 'Please contact your manager',
    todaysShift: 'Today\'s Shift',
    toConfirm: 'To Confirm',
    awaitingConfirmation: 'Awaiting Confirmation',
    assignSelf: 'Assign Yourself',
    unassign: 'Unassign',
    maxTablesReached: 'Maximum tables reached',
    assignedTables: 'Assigned Tables',
    assignYourself: 'Assign Yourself',
    myTables: 'My Tables',
    availableTables: 'Available Tables',
    assignYourselfToTables: 'Assign Yourself to Tables',
    pickAvailableTables: 'Pick available tables to serve (max 5 tables)',
    clickToAssign: 'Click to assign',
    currentlyViewing: 'Currently viewing:',
    stationView: 'Station View',
    selectWhatToDisplay: 'Select what orders to display',
    kitchenOnly: 'Kitchen Only',
    barOnly: 'Bar Only',
    bothStations: 'Both Stations',
    noActiveOrder: 'No active order found.',
    couldNotFetchOrder: 'Could not fetch active order',
    pleaseAddItems: 'Please add items to order',
    itemsAdded: 'Items added to order',
    failedToAddItems: 'Failed to add items',
    addItemsToOrder: 'Add Items to Order',
    currentTotal: 'Current Total',
    newTotal: 'New Total',
    addedSuccessfully: 'Items added successfully',
    noActiveOrders: 'No active orders',
    inKitchen: 'In Kitchen',
    readyToServe: 'Ready to Serve',
    note: 'Note',
    orderedAt: 'Ordered at',
    confirmOrder: 'Confirm Order',
    noPendingConfirmations: 'No pending confirmations',
    reviewConfirmOrders: 'Review and confirm QR orders',
    sessionExpired: 'Session expired. Please login again.',
    accessDenied: 'Access denied',
    failedToLoadOrders: 'Failed to load orders',
    orderDetails: 'Order Details',
    viewDetails: 'View Details',
    orderDate: 'Order Date',
    totalAmount: 'Total Amount',
    customerInfo: 'Customer Information',
    enterPhoneToViewOrders: 'Enter your phone number to view your orders',
    enterPhoneNumber: 'Enter your phone number',
    viewOrders: 'View Orders',
    noOrdersFound: 'No orders found',
    recentOrders: 'Recent Orders',
    orderHistory: 'Order History',
    loyaltyPoints: 'Loyalty Points',
    points: 'points',
    statistics: 'Statistics',
    favoriteItems: 'Favorite Items',
    totalVisits: 'Total Visits',
    visits: 'Visits',
    notProvided: 'Not provided',
    noTablesFound: 'No tables found',
    notAssigned: 'Not assigned',
    assignWaiterToTable: 'Assign Waiter to Table',
    noWaiterAssigned: 'No waiter assigned',
    assign: 'Assign',
    pendingOrderWaiting: 'Pending order waiting',
    orderConfirmed: 'Order confirmed! Sent to kitchen.',
    noTablesFound: 'No tables found',
    addYourFirstTable: 'Add your first table',

    // ---------- QR CODE ORDERING ----------
    qrCodeAvailable: 'QR Code available',
    getQRCode: 'Get QR Code',
    qrCodeForTable: 'QR Code for Table',
    customersScanToOrder: 'Customers scan to view menu and order',
    qrCodeInstructions: 'Share this link with customers. They can scan the QR code to view the menu and place orders from their phone.',
    qrUrl: 'QR URL',
    copyQrUrl: 'Copy QR URL',
    qrNote: 'You can generate a physical QR code using any QR code generator website by pasting this URL.',
    printQRCodes: 'Print QR Codes',
    generateAndPrintQRCodes: 'Generate and print QR codes for all tables',
    printAll: 'Print All',
    copyUrl: 'Copy URL',
    qrPrintInstructions: 'Print this page and cut out each QR code. Place them on corresponding tables.',
    cutAndPlaceOnTables: 'Cut and place QR codes on corresponding tables.',
    howQrWorks: 'How QR Ordering Works',
    step1: 'Scan QR code at your table',
    step2: 'Browse menu and add items',
    step3: 'Enter your details',
    step4: 'Place order - waiter confirms',
    scanToOrder: 'Scan to Order',
    viewMenu: 'View Menu',
    urlCopied: 'URL copied',
    yourOrderIsReady: 'Your order is ready for pickup!',
    orderCompletedThankYou: 'Order completed! Thank you for dining with us!',

    // ---------- INVENTORY MANAGEMENT ----------
    inventoryManagement: 'Inventory Management',
    manageProductsAndIngredients: 'Manage products and ingredients',
    ingredients: 'Ingredients',
    products: 'Products',
    addIngredient: 'Add Ingredient',
    addProduct: 'Add Product',
    stock: 'Stock',
    minStock: 'Min Stock',
    unit: 'Unit',
    unitCost: 'Unit Cost',
    category: 'Category',
    supplier: 'Supplier',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    adjustStock: 'Adjust Stock',
    currentStock: 'Current Stock',
    lowStockDescription: 'The following ingredients are below minimum stock level:',
    left: 'left',
    min: 'Min',
    moreItems: 'more items',
    noIngredientsFound: 'No ingredients found',
    noProductsFound: 'No products found',
    ingredientsBelowMinStock: 'ingredients are below minimum stock level',
    selectUnit: 'Select unit',
    kilogram: 'Kilogram (kg)',
    gram: 'Gram (g)',
    liter: 'Liter (L)',
    milliliter: 'Milliliter (ml)',
    pieces: 'Pieces (pcs)',
    egVegetables: 'e.g., Vegetables',
    stockValue: 'Stock Value',
    reorderLevel: 'Reorder Level',
    available: 'Available',
    unavailable: 'Unavailable',

    // ---------- WASTAGE TRACKING ----------
    wastageTracking: 'Wastage Tracking',
    trackIngredientWaste: 'Track ingredient waste from trimming, spoilage, and cooking loss',
    wastagePercentage: 'Wastage Factor (%)',
    cookingLoss: 'Cooking Loss (%)',
    yieldPercentage: 'Yield Percentage (%)',
    expectedUsage: 'Expected Usage',
    actualUsage: 'Actual Usage',
    wastageAmount: 'Wastage Amount',
    wastageCost: 'Wastage Cost',
    totalWastageCost: 'Total Wastage Cost',
    wastageReport: 'Wastage Report',
    wastageByIngredient: 'Wastage by Ingredient',
    dailyWastage: 'Daily Wastage',
    wastageDescription: 'When making food, not all ingredients are used 100%. Some is lost to trimming, spoilage, spillage, and cooking evaporation.',
    wastageExample: 'Example: 250g beef + 15% wastage = 287.5g deducted from inventory',
    trimmingWaste: 'Trimming & Spoilage',
    cookingEvaporation: 'Cooking Evaporation (shrinkage)',
    batchCooking: 'Batch Cooking Efficiency',
    autoWastageLearning: 'Auto-learning wastage factors from historical data',
    lowStockCritical: 'Critical - Reorder Now',
    wastageAlert: 'High Wastage Alert',
    wastageReductionTip: 'Tip: Track wastage to reduce costs by 5-15%',
    ingredientCostBreakdown: 'Ingredient Cost Breakdown',
    defaultWastage: 'Default Wastage',
    defaultWastagePercentage: 'Default Wastage %',
    defaultCookingLossPercentage: 'Default Cooking Loss %',
    wastageSettings: 'Wastage Settings',

    // ---------- EXPENSE TRACKING ----------
    expenseTracking: 'Expense Tracking',
    trackBusinessOperationalCosts: 'Track business operational costs',
    addExpense: 'Add Expense',
    expenses: 'Expenses',
    expenseCategory: 'Expense Category',
    rent: 'Rent',
    utilities: 'Utilities',
    salaries: 'Salaries',
    marketing: 'Marketing',
    maintenance: 'Maintenance',
    supplies: 'Supplies',
    transport: 'Transport',
    insurance: 'Insurance',
    taxes: 'Taxes',
    other: 'Other',
    recordedBy: 'Recorded By',
    expenseDate: 'Expense Date',
    thisMonth: 'This Month',
    thisYear: 'This Year',
    from: 'From',
    to: 'To',
    totalExpenses: 'Total Expenses',
    averageDaily: 'Average Daily',
    perDay: 'Per day',
    categories: 'Categories',
    differentExpenseTypes: 'Different expense types',
    expenseByCategory: 'Expense by Category',
    transactions: 'transactions',
    searchExpenses: 'Search expenses...',
    noExpensesFound: 'No expenses found',
    editExpense: 'Edit Expense',
    selectCategory: 'Select category',
    optionalDescription: 'Optional description...',
    monthlyExpenses: 'Monthly Expenses',
    expenseTrend: 'Expense Trend',

    // ---------- PROFIT REPORTS ----------
    profitReports: 'Profit Reports',
    trackYourBusinessProfitability: 'Track your business profitability',
    totalRevenue: 'Total Revenue',
    totalCost: 'Total Cost',
    totalProfit: 'Total Profit',
    profitMargin: 'Profit Margin',
    dailyBreakdown: 'Daily Breakdown',
    topProducts: 'Top Products',
    byProfitContribution: 'By profit contribution',
    sold: 'Sold',
    revenue: 'Revenue',
    cost: 'Cost',
    profit: 'Profit',
    margin: 'Margin',
    averageOrder: 'Average Order',
    todayPerformance: "Today's Performance",
    revenueProfitTrend: 'Revenue & Profit Trend',
    hourlySalesTrend: 'Hourly Sales Trend',
    hour: 'Hour',
    product: 'Product',
    report: 'Report',
    generated: 'Generated',
    exportFailed: 'Failed to export',
    pdfExportError: 'PDF Export Error',
    exportExcel: 'Export Excel',
    exportPDF: 'Export PDF',
    noDataToExport: 'No data to export',
    salesReports: 'Sales Reports',
    performanceByDay: 'Performance by day',
    noSalesDataForPeriod: 'No sales data for selected period',
    grossProfit: 'Gross Profit',
    netProfit: 'Net Profit',
    operatingExpenses: 'Operating Expenses',

    // ---------- STAFF MANAGEMENT ----------
    staffManagement: 'Staff Management',
    manageStaffAccountsAndPermissions: 'Manage staff accounts and permissions',
    addStaff: 'Add Staff',
    editStaff: 'Edit Staff',
    deleteStaff: 'Delete Staff',
    fullName: 'Full Name',
    joinDate: 'Join Date',
    lastLogin: 'Last Login',
    pendingApproval: 'Pending Approval',
    active: 'Active',
    inactive: 'Inactive',
    pendingApprovals: 'Pending Approvals',
    reviewAndApproveStaffAccounts: 'Review and approve new staff account requests',
    defaultRole: 'Default Role',
    userApproved: 'User approved successfully',
    userRejected: 'User rejected',
    waitingForApproval: 'Waiting for admin approval',
    staffPerformance: 'Staff Performance',
    salesPerformance: 'Sales Performance',
    moreStaff: 'more staff members',
    noSalesData: 'No sales data available for this period',
    topPerformer: '🏆 TOP PERFORMER',
    noStaffMembersFound: 'No staff members found',
    accessDeniedOnlyOwners: 'Access denied. Only owners and admins can view staff.',
    failedToLoadStaff: 'Failed to load staff',
    staffUpdatedSuccessfully: 'Staff member updated successfully!',
    staffCreatedSuccessfully: 'Staff member created successfully!',
    failedToSaveStaff: 'Failed to save staff member',
    deleteStaffConfirm: 'Are you sure you want to delete this staff member?',
    staffDeletedSuccessfully: 'Staff member deleted successfully!',
    failedToDeleteStaff: 'Failed to delete staff member',
    roles: 'Roles',
    clickAddStaffToCreate: 'Click "Add Staff" to create a new account',
    editStaffMember: 'Edit Staff Member',
    addNewStaffMember: 'Add New Staff Member',
    enterFullName: 'Enter full name',
    enterEmailAddress: 'Enter email address',
    minimum6Characters: 'Minimum 6 characters',
    fullAccess: 'Full Access',
    operationalAccess: 'Operational Access',
    paymentOnly: 'Payment Only',
    orderTaking: 'Order Taking',
    foodPrepOnly: 'Food Prep Only',
    phoneNumber: 'Phone Number',
    optional: 'Optional',
    updateStaff: 'Update Staff',
    createStaff: 'Create Staff',
    accessDeniedOnlyOwnersAndAdmins: 'Access denied. Only owners and admins can view pending approvals.',
    failedToLoadPendingUsers: 'Failed to load pending users',
    userApprovedSuccessfully: 'User approved successfully! They can now login.',
    failedToApproveUser: 'Failed to approve user',
    rejectUserConfirm: 'Are you sure you want to reject this user?',
    userRejectedAndRemoved: 'User rejected and removed.',
    failedToRejectUser: 'Failed to reject user',
    usersWaiting: 'users waiting',
    allStaffAccountsApproved: 'All staff accounts have been approved',
    newStaffWillAppearHere: 'When new staff sign up, they will appear here',
    notProvided: 'Not provided',
    requested: 'Requested',
    assignRole: 'Assign Role',
    basicAccess: 'Basic Access',
    operations: 'Operations',
    tipApprovedUsersWillReceiveEmail: 'Approved users will receive an email notification',

    // ---------- RECIPE MANAGEMENT ----------
    recipeManagement: 'Recipe Management',
    defineProductRecipes: 'Define product recipes for automatic stock deduction',
    howRecipesWork: 'How Recipes Work',
    recipeDescription: 'Each product needs a recipe that lists all ingredients and quantities.',
    setupRecipe: 'Setup Recipe',
    viewRecipe: 'View Recipe',
    calculateCost: 'Calculate Cost',
    ingredientsNeeded: 'Ingredients Needed',
    totalIngredientCost: 'Total Ingredient Cost',
    profitSummary: 'Profit Summary',
    sellingPrice: 'Selling Price',
    ingredientCost: 'Ingredient Cost',
    recipeExists: 'Recipe configured',
    noRecipe: 'No recipe configured',
    failedToLoadRecipe: 'Failed to load recipe',
    pleaseSelectIngredientAndQuantity: 'Please select an ingredient and enter quantity',
    pleaseAddAtLeastOneIngredient: 'Please add at least one ingredient',
    recipeSavedSuccessfully: 'Recipe saved successfully!',
    failedToSaveRecipe: 'Failed to save recipe',
    noRecipeFoundForProduct: 'No recipe found for this product',
    uncategorized: 'Uncategorized',
    recipe: 'Recipe',
    noIngredientsAddedYet: 'No ingredients added yet',
    selectIngredient: 'Select Ingredient',
    quantityRequired: 'Quantity Required',
    saveRecipe: 'Save Recipe',
    yieldQuantity: 'Yield Quantity',

    // ---------- CUSTOMERS ----------
    customerManagement: 'Customer Management',
    manageCustomerAccounts: 'Manage customer accounts and loyalty',
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerDetails: 'Customer Details',
    totalCustomers: 'Total Customers',
    totalLoyaltyPoints: 'Total Loyalty Points',
    totalSpent: 'Total Spent',
    avgSpentPerCustomer: 'Average per Customer',
    searchCustomers: 'Search customers...',
    noCustomersFound: 'No customers found',
    addYourFirstCustomer: 'Add your first customer',
    customerAddress: 'Customer address',
    specialNotes: 'Special notes',
    totalVisits: 'Total Visits',
    customerCreated: 'Customer created successfully',
    customerUpdated: 'Customer updated successfully',
    customerDeleted: 'Customer deleted successfully',
    deleteCustomerConfirm: 'Are you sure you want to delete this customer?',
    lastVisit: 'Last Visit',

    // ---------- SETTINGS / RECEIPT ----------
    receiptFooter: 'Receipt Footer Message',
    restaurantName: 'Restaurant Name',
    address: 'Address',
    workingHours: 'Working Hours',
    taxRate: 'Tax Rate',
    configureRestaurantPreferences: 'Configure your restaurant preferences',
    settingsSavedSuccessfully: 'Settings saved successfully!',
    restaurantInformation: 'Restaurant Information',
    businessSettings: 'Business Settings',
    receiptSettings: 'Receipt Settings',
    thankYouForDining: 'Thank you for dining with us!',
    saveSettings: 'Save Settings',
    settingsSaveInfo: 'Settings are saved to your browser.',

    // ---------- REAL-TIME NOTIFICATIONS ----------
    lowStockAlert: 'Low Stock Alert',
    newOrderAlert: 'New Order Alert',
    orderReadyAlert: 'Order Ready Alert',
    salesReportReady: 'Sales Report Ready',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    orderStatusUpdated: 'Order status updated',
    tableStatusUpdated: 'Table status updated',

    // ---------- ORDER CANCELLATION ----------
    cancelOrderTitle: 'Cancel Order',
    voidOrderTitle: 'Void Order',
    cancellationReasonPlaceholder: 'Why is this order being cancelled?',
    voidReasonPlaceholder: 'Why is this order being voided?',
    voidDescription: 'Void removes order from sales records and restores stock.',
    customerChangedMind: 'Customer changed mind',
    customerLeft: 'Customer left restaurant',
    orderTooLong: 'Order took too long',
    wrongItems: 'Wrong items ordered',
    duplicateOrder: 'Duplicate order',
    paymentIssue: 'Payment issue',
    kitchenCannotPrepare: 'Kitchen cannot prepare',
    systemError: 'System error - double charge',
    trainingError: 'Staff training error',
    testOrder: 'Test order',
    wrongTable: 'Wrong table charged',
    overcharged: 'Customer overcharged',
    cancellationReason: 'Cancellation Reason',
    yesCancel: 'Yes, Cancel',
    noKeep: 'No, Keep',
    cancellationPlaceholder: 'Why is this order being cancelled?',

    // ---------- DASHBOARD ----------
    businessPerformance: 'Business performance overview',
    todayRevenue: "Today's Revenue",
    todayProfit: "Today's Profit",
    monthRevenue: 'Month Revenue',
    monthProfit: 'Month Profit',
    weeklyTrend: 'Weekly Trend',
    monthlyTrend: 'Monthly Trend',
    yearlyTrend: 'Yearly Trend',
    topSellingProducts: 'Top Selling Products',
    recentSales: 'Recent Sales',
    paymentMethods: 'Payment Methods',
    hourlySales: 'Hourly Sales',
    dailyOrders: 'Daily Orders',
    totalProducts: 'Total Products',
    needReorder: 'Need reorder',
    critical: 'Critical',
    latestTransactions: 'Latest transactions',
    cashier: 'Cashier',
    system: 'System',
    noSalesYet: 'No sales yet',
    weekRevenue: 'Week Revenue',
    gross: 'Gross',
    netProfitMargin: 'Net Profit Margin',
    quickSummary: 'Quick Summary',
    avgOrderValue: 'Avg Order Value',
    ownerDashboard: 'Owner Dashboard',
    fullBusinessAnalytics: 'Full business analytics and control',
    totalStaff: 'Total Staff',
    activeEmployees: 'Active employees',
    totalOrders: 'Total Orders',
    monthNetProfit: 'Month Net Profit',

    // ---------- MANAGER DASHBOARD ----------
    managerDashboard: 'Manager Dashboard',
    operationalOverview: 'Operational overview',
    todaySales: "Today's Sales",
    staffOnDuty: 'Staff on Duty',
    ingredientsNeedReorder: 'ingredients need reordering',
    updateInventory: 'Update Inventory',
    addOrEditStockLevels: 'Add or edit stock levels',
    viewReports: 'View Reports',
    salesAndProfitAnalytics: 'Sales and profit analytics',

    // ---------- AUTHENTICATION / LOGIN ----------
    restaurantManagementSystem: 'Restaurant Management System',
    emailAddress: 'Email Address',
    loggingIn: 'Logging in...',
    signIn: 'Sign In',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    demoAccounts: 'Demo Accounts',
    createAccount: 'Create your account',
    fullNamePlaceholder: 'John Doe',
    passwordMinLengthPlaceholder: 'Min 6 characters',
    passwordMinLengthHint: 'Minimum 6 characters',
    creatingAccount: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    accountCreated: 'Account Created!',
    accountPendingApproval: 'Your account has been created and is pending admin approval.',
    goToLogin: 'Go to Login',
    signupFailed: 'Signup failed',
    emailPasswordRequired: 'Email and password are required',
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid email or password',
    accountPending: 'Account pending approval. Please wait.',
    accountDeactivated: 'Account deactivated. Contact admin.',
    networkError: 'Network error. Please check your connection.',
    saveSuccess: 'Saved successfully',
    requiredField: 'This field is required',
    passwordMinLength: 'Password must be at least 6 characters',
    emailInvalid: 'Please enter a valid email address',
    stockInsufficient: 'Insufficient stock',
    invalidEmailOrPassword: 'Invalid email or password',

    // ---------- TIME PERIODS ----------
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last365Days: 'Last 365 Days',
    week: 'Week',
    month: 'Month',
    year: 'Year',
    today: 'Today',
    yesterday: 'Yesterday',
    tomorrow: 'Tomorrow',

    // ---------- WEEK DAYS ----------
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',

    // ---------- MONTHS ----------
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',

    // ---------- SALES ----------
    sales: 'Sales',
    avgOrder: 'Avg Order',
    only: 'Only',
    customers: 'Customers',

    // ---------- ASSIGN WAITERS ----------
    assignWaitersToTables: 'Assign Waiters to Tables',
    assignWaitersDescription: 'Assign waiters to manage specific tables',
    assignWaitersInfo: 'Waiters will receive notifications for orders at their assigned tables',
    availableWaiters: 'Available Waiters',
    assignedTables: 'Assigned Tables',
    currentStatus: 'Current Status',
    assignedWaiter: 'Assigned Waiter',
    selectWaiter: 'Select Waiter',
    waiterAssigned: 'Waiter assigned',
    noWaitersAvailable: 'No waiters available',
    addWaitersFirst: 'Please add waiters first',
    failedToLoadData: 'Failed to load data',
    waiterAssignedSuccessfully: 'Waiter assigned successfully',
    failedToAssignWaiter: 'Failed to assign waiter',

    // ---------- MANAGE TABLES ----------
    addEditRemoveTables: 'Add, edit, or remove restaurant tables',
    addTable: 'Add Table',
    editTable: 'Edit Table',
    totalTables: 'Total Tables',
    reservedCleaning: 'Reserved / Cleaning',
    addNewTable: 'Add New Table',
    tableNumber: 'Table Number',
    initialStatus: 'Initial Status',
    newTableNote: 'New tables will be available for seating',
    failedToSaveTable: 'Failed to save table',
    deleteTableConfirm: 'Are you sure you want to delete this table?',
    failedToDeleteTable: 'Failed to delete table',
    updatedSuccessfully: 'updated successfully',
    createdSuccessfully: 'created successfully',
    deletedSuccessfully: 'deleted successfully',
    qrUrlCopied: 'QR URL copied',

    // ---------- PRODUCT PAGES ----------
    productUpdatedSuccessfully: 'Product updated successfully!',
    productCreatedSuccessfully: 'Product created successfully!',
    productDeletedSuccessfully: 'Product deleted successfully',

    // ============================================
// SIDEBAR MENU ITEMS
// ============================================
tableManagement: 'Table Management',
myOrders: 'My Orders',
confirmOrders: 'Confirm Orders',
posTerminal: 'POS Terminal',
manualOrder: 'Manual Order',
tableStatus: 'Table Status',
kitchenOrders: 'Orders',

// ============================================
// CASHIER PAGE
// ============================================
readyForPayment: 'Ready for Payment',
salesHistory: 'Sales History',

// ============================================
// KITCHEN BUTTONS
// ============================================
startCooking: 'Start Cooking',
markReady: 'Mark Ready',
readyForPickup: 'Ready for Pickup',
noOrdersToDisplay: 'No orders to display',
ordersWillAppearHere: 'Orders will appear here when created',
pending: 'Pending',
preparing: 'Preparing',
ready: 'Ready',
active: 'Active',
order: 'Order',
items: 'Items',
more: 'more',
customer: 'Customer',
table: 'Table',
waitingTime: 'Waiting Time',
kitchenStatus: 'Kitchen Status',
failedToUpdateOrderStatus: 'Failed to update order status',
newOrderReceived: 'New order received',
orderSent: 'Order sent to kitchen',
  },

  // ==========================================================
  // AMHARIC TRANSLATIONS (አማርኛ)
  // ==========================================================
  am: {
    // ---------- COMMON UI ----------
    dashboard: 'ዳሽቦርድ',
    logout: 'ውጣ',
    welcome: 'እንኳን ደህና መጡ',
    readyToServe: 'ደንበኞችን ለማገልገል ዝግጁ',
    search: 'ፈልግ...',
    notifications: 'ማሳወቂያዎች',
    settings: 'ቅንብሮች',
    save: 'አስቀምጥ',
    cancel: 'ሰርዝ',
    delete: 'ሰርዝ',
    edit: 'አርትዕ',
    refresh: 'አድስ',
    approve: 'ፈቅድ',
    reject: 'አትፍቀድ',
    back: 'ተመለስ',
    confirm: 'አረጋግጥ',
    loading: 'በመጫን ላይ...',
    noData: 'ምንም መረጃ የለም',
    actions: 'ድርጊቶች',
    status: 'ሁኔታ',
    date: 'ቀን',
    time: 'ሰዓት',
    total: 'ጠቅላላ',
    amount: 'መጠን',
    description: 'መግለጫ',
    name: 'ስም',
    email: 'ኢሜይል',
    phone: 'ስልክ',
    password: 'የይለፍ ቃል',
    role: 'ሚና',
    loggedInAs: 'ገብተዋል እንደ',
    submit: 'አስገባ',
    update: 'አዘምን',
    create: 'ፍጠር',
    close: 'ዝጋ',
    export: 'ላክ',
    import: 'አምጣ',
    print: 'አትም',
    download: 'አውርድ',
    upload: 'ስቀል',
    yes: 'አዎ',
    no: 'አይ',
    ok: 'እሺ',
    error: 'ስህተት',
    success: 'ተሳካ',
    warning: 'ማስጠንቀቂያ',
    info: 'መረጃ',
    order_taker: 'ትዕዛዝ መቀበያ',
    station: 'ጣቢያ',
    addNew: 'አዲስ ጨምር',
    safetyStock: 'የደህንነት ክምችት',
    selectCategory: 'ምድብ ምረጥ',
    saveFailed: 'ማስቀመጥ አልተሳካም',
    deleteFailed: 'መሰረዝ አልተሳካም',
    deleteConfirm: 'ይህንን መሰረዝ እርግጠኛ ነዎት?',
    ingredient: 'ጥሬ እቃ',
    product: 'ምርት',
    currencySymbol: 'ብር',
    currency: 'ብር',

    // ---------- USER ROLES ----------
    owner: 'ባለቤት',
    manager: 'አስተዳዳሪ',
    cashier: 'ገንዘብ ተቀባይ',
    waiter: 'አስተናጋጅ',
    kitchen: 'ኩሽና',
    admin: 'አስተዳዳሪ',
    staff: 'ሰራተኛ',

    // ---------- DARK MODE ----------
    darkMode: 'ጨለማ ሁነታ',
    lightMode: 'ብርሃን ሁነታ',
    theme: 'ገጽታ',

    // ---------- POS / CASHIER ----------
    posTerminal: 'የሽያጭ መዝገብ',
    currentOrder: 'የአሁኑ ትዕዛዝ',
    cartEmpty: 'ጋሪ ባዶ ነው',
    checkout: 'ክፈል',
    subtotal: 'ንዑስ ድምር',
    vat: 'ተ.እ.ታ (15%)',
    tax: 'ግብር',
    paymentMethod: 'የክፍያ ዘዴ',
    cash: 'ጥሬ ገንዘብ',
    card: 'ካርድ',
    mobile: 'ሞባይል',
    completeOrder: 'ትዕዛዝ አጠናቅቅ',
    processPayment: 'ክፍያ አስኬድ',
    customerName: 'የደንበኛ ስም',
    customerPhone: 'የደንበኛ ስልክ',
    addToCart: 'ወደ ጋሪ ጨምር',
    quantity: 'ብዛት',
    items: 'እቃዎች',
    salesHistory: 'የሽያጭ ታሪክ',
    readyForPayment: 'ለክፍያ ዝግጁ',
    addToOrder: '+ ወደ ትዕዛዝ ጨምር',
    tapToAdd: 'ለመጨመር ምግቦችን ይንኩ',
    manualOrder: 'በእጅ ትዕዛዝ',
    walkInCustomer: 'ያለቀጠሮ ደንበኛ',
    proceedToCheckout: 'ወደ ክፍያ ሂድ',
    clearCart: 'ጋሪ አጽዳ',
    orderSent: 'ትዕዛዝ ወደ ኩሽና ተልኳል',
    noOrdersReady: 'ለክፍያ ዝግጁ የሆኑ ትዕዛዞች የሉም',
    ordersFromKitchenWillAppear: 'ከኩሽና የሚመጡ ትዕዛዞች እዚህ ይታያሉ',
    payment: 'ክፍያ',
    orderTotal: 'ጠቅላላ ትዕዛዝ',
    complete: 'አጠናቅቅ',
    paymentSuccessful: 'ክፍያ ተሳክቷል!',
    paymentFailed: 'ክፍያ አልተሳካም',
    ordersReady: 'ትዕዛዞች ዝግጁ',
    readySince: 'ዝግጁ የሆነው ከ',
    customer: 'ደንበኛ',

    // ---------- KITCHEN ----------
    kitchenDashboard: 'የኩሽና ዳሽቦርድ',
    manageFoodPreparation: 'ምግብ ዝግጅት ያስተዳድሩ',
    pending: 'በመጠባበቅ ላይ',
    preparing: 'በዝግጅት ላይ',
    ready: 'ዝግጁ',
    completed: 'ተጠናቋል',
    cancelled: 'ተሰርዟል',
    startCooking: 'ማብሰል ጀምር',
    markReady: 'ዝግጁ ምልክት አድርግ',
    readyForPickup: 'ለማንሳት ዝግጁ',
    newOrderReceived: 'አዲስ ትዕዛዝ ደርሷል',
    cooking: 'በማብሰል ላይ',
    ordersToPrepare: 'ለዝግጅት ያሉ ትዕዛዞች',
    active: 'ንቁ',
    noOrdersToDisplay: 'ለማሳየት ምንም ትዕዛዞች የሉም',
    ordersWillAppearHere: 'ትዕዛዞች ሲፈጠሩ እዚህ ይታያሉ',
    kitchenStatus: 'የኩሽና ሁኔታ',
    waitingTime: 'የጥበቃ ጊዜ',
    failedToUpdateOrderStatus: 'የትዕዛዝ ሁኔታ ማዘመን አልተቻለም',
    newOrdersWaiting: 'አዲስ ትዕዛዞች ለኩሽና በመጠባበቅ ላይ',
    isNow: 'አሁን ነው',
    order: 'ትዕዛዝ',

    // ---------- WAITER / TABLE ----------
    tableManagement: 'የጠረጴዛ አያያዝ',
    selectTable: 'ትዕዛዝ ለመጀመር ጠረጴዛ ይምረጡ',
    floorPlan: 'የሬስቶራንቱ እቅድ',
    available: 'ክፍት',
    occupied: 'ተይዟል',
    reserved: 'ተይዟል',
    cleaning: 'በጽዳት ላይ',
    capacity: 'አቅም',
    table: 'ጠረጴዛ',
    orderForTable: 'ለጠረጴዛ ትዕዛዝ',
    specialInstructions: 'ልዩ መመሪያዎች',
    sendToKitchen: 'ወደ ኩሽና ላክ',
    activeOrders: 'ንቁ ትዕዛዞች',
    yourActiveOrders: 'የእርስዎ ንቁ ትዕዛዞች',
    orderNumber: 'የትዕዛዝ ቁጥር',
    cancelOrder: 'ትዕዛዝ ሰርዝ',
    addMoreItems: 'ተጨማሪ እቃዎች ጨምር',
    addItems: 'እቃዎች ጨምር',
    activeOrdersHidden: 'የተደበቁ ትዕዛዞች',
    showOrders: 'ትዕዛዞች አሳይ',
    noActiveOrdersMessage: 'ምንም ንቁ ትዕዛዞች የሉም',
    myOrders: 'የኔ ትዕዛዞች',
    manageTables: 'ጠረጴዛዎችዎን እና ትዕዛዞችዎን ያስተዳድሩ',
    hide: 'ደብቅ',
    clickToCreateOrder: 'ትዕዛዝ ለመፍጠር ጠቅ ያድርጉ',
    clickToAddItems: 'እቃዎችን ለመጨመር ጠቅ ያድርጉ',
    newOrderForTable: 'አዲስ ትዕዛዝ ለጠረጴዛ',
    seats: 'መቀመጫዎች',
    searchMenu: 'ምናሌ ፈልግ...',
    allItems: 'ሁሉም እቃዎች',
    sending: 'በመላክ ላይ...',
    itemsToAdd: 'ለመጨመር ያሉ እቃዎች',
    noItemsSelected: 'ምንም እቃዎች አልተመረጡም',
    adding: 'በመጨመር ላይ...',
    isReserved: 'ተይዟል',
    isCleaning: 'በጽዳት ላይ ነው',
    orderSentKitchen: 'ትዕዛዝ ወደ ኩሽና ተልኳል',
    failedToSubmitOrder: 'ትዕዛዙን ማስገባት አልተቻለም',
    orderCancelledSuccess: 'ትዕዛዝ በተሳካ ሁኔታ ተሰርዟል!',
    failedToCancelOrder: 'ትዕዛዙን መሰረዝ አልተቻለም',
    pendingConfirmations: 'ትዕዛዞችን አረጋግጥ',
    tableStatus: 'የጠረጴዛ ሁኔታ',
    manageTableAvailability: 'የጠረጴዛ አቅርቦት እና ሁኔታ ያስተዳድሩ',
    changeStatus: 'ሁኔታ ቀይር',
    yourAssignedTables: 'የተመደቡልዎት ጠረጴዛዎች',
    noTablesAssigned: 'ምንም ጠረጴዛዎች አልተመደቡም',
    contactManager: 'እባክዎ አስተዳዳሪዎን ያነጋግሩ',
    todaysShift: 'የዛሬ ፈረቃ',
    toConfirm: 'ለማረጋገጥ',
    awaitingConfirmation: 'ማረጋገጫ በመጠባበቅ ላይ',
    assignSelf: 'ራስዎን መድቡ',
    unassign: 'አላስፈላጊ',
    maxTablesReached: 'ከፍተኛ ጠረጴዛዎች ላይ ደርሰዋል',
    assignedTables: 'የተመደቡ ጠረጴዛዎች',
    assignYourself: 'ራስዎን ይመድቡ',
    myTables: 'የኔ ጠረጴዛዎች',
    availableTables: 'ክፍት ጠረጴዛዎች',
    assignYourselfToTables: 'ራስዎን ለጠረጴዛዎች ይመድቡ',
    pickAvailableTables: 'ለማገልገል ክፍት ጠረጴዛዎችን ይምረጡ (ከፍተኛ 5 ጠረጴዛዎች)',
    clickToAssign: 'ለመመደብ ይጫኑ',
    currentlyViewing: 'በአሁኑ ጊዜ እያዩ ያለው:',
    stationView: 'የጣቢያ እይታ',
    selectWhatToDisplay: 'ምን ትዕዛዞች እንደሚታዩ ይምረጡ',
    kitchenOnly: 'ኩሽና ብቻ',
    barOnly: 'ባር ብቻ',
    bothStations: 'ሁለቱም ጣቢያዎች',
    noActiveOrder: 'ምንም ንቁ ትዕዛዝ አልተገኘም',
    couldNotFetchOrder: 'ንቁ ትዕዛዝ ማግኘት አልተቻለም',
    pleaseAddItems: 'እባክዎ እቃዎችን ወደ ትዕዛዝ ይጨምሩ',
    itemsAdded: 'እቃዎች ወደ ትዕዛዝ ተጨምረዋል',
    failedToAddItems: 'እቃዎችን መጨመር አልተቻለም',
    addItemsToOrder: 'እቃዎችን ወደ ትዕዛዝ ጨምር',
    currentTotal: 'የአሁኑ ድምር',
    newTotal: 'አዲስ ድምር',
    addedSuccessfully: 'እቃዎች በተሳካ ሁኔታ ተጨምረዋል',
    noActiveOrders: 'ምንም ንቁ ትዕዛዞች የሉም',
    inKitchen: 'በኩሽና ውስጥ',
    readyToServe: 'ለማገልገል ዝግጁ',
    note: 'ማስታወሻ',
    orderedAt: 'የታዘዘው በ',
    confirmOrder: 'ትዕዛዝ አረጋግጥ',
    noPendingConfirmations: 'ምንም በመጠባበቅ ላይ ያሉ ማረጋገጫዎች የሉም',
    reviewConfirmOrders: 'የQR ትዕዛዞችን ይገምግሙ እና ያረጋግጡ',
    sessionExpired: 'ክፍለ ጊዜ አልቋል። እባክዎ እንደገና ይግቡ።',
    accessDenied: 'መድረስ አልተፈቀደም',
    failedToLoadOrders: 'ትዕዛዞችን መጫን አልተቻለም',
    orderDetails: 'የትዕዛዝ ዝርዝሮች',
    viewDetails: 'ዝርዝሮችን ይመልከቱ',
    orderDate: 'የትዕዛዝ ቀን',
    totalAmount: 'ጠቅላላ መጠን',
    customerInfo: 'የደንበኛ መረጃ',
    enterPhoneToViewOrders: 'ትዕዛዞችዎን ለማየት ስልክ ቁጥርዎን ያስገቡ',
    enterPhoneNumber: 'ስልክ ቁጥርዎን ያስገቡ',
    viewOrders: 'ትዕዛዞችን ይመልከቱ',
    noOrdersFound: 'ምንም ትዕዛዞች አልተገኙም',
    recentOrders: 'የቅርብ ጊዜ ትዕዛዞች',
    orderHistory: 'የትዕዛዝ ታሪክ',
    loyaltyPoints: 'የታማኝነት ነጥቦች',
    points: 'ነጥቦች',
    statistics: 'ስታቲስቲክስ',
    favoriteItems: 'ተወዳጅ እቃዎች',
    totalVisits: 'ጠቅላላ ጉብኝቶች',
    visits: 'ጉብኝቶች',
    notProvided: 'አልቀረበም',
    noTablesFound: 'ምንም ጠረጴዛዎች አልተገኙም',
    notAssigned: 'አልተመደበም',
    assignWaiterToTable: 'አስተናጋጅ ለጠረጴዛ መድብ',
    noWaiterAssigned: 'ምንም አስተናጋጅ አልተመደበም',
    assign: 'መድብ',
    pendingOrderWaiting: 'በመጠባበቅ ላይ ያለ ትዕዛዝ',
    orderConfirmed: 'ትዕዛዝ ተረጋግጧል! ወደ ኩሽና ተልኳል።',
    noTablesFound: 'ምንም ጠረጴዛዎች አልተገኙም',
    addYourFirstTable: 'የመጀመሪያ ጠረጴዛዎን ያክሉ',

    // ---------- QR CODE ----------
    qrCodeAvailable: 'QR ኮድ ይገኛል',
    getQRCode: 'QR ኮድ አግኝ',
    qrCodeForTable: 'ለጠረጴዛ QR ኮድ',
    customersScanToOrder: 'ደንበኞች ምናሌውን ለማየት እና ለማዘዝ ይቃኙ',
    qrCodeInstructions: 'ይህን አገናኝ ከደንበኞች ጋር ያጋሩ። QR ኮዱን በመቅኝት ምናሌውን ማየት እና ትዕዛዝ ማስቀመጥ ይችላሉ።',
    qrUrl: 'QR አገናኝ',
    copyQrUrl: 'QR አገናኝ ቅዳ',
    qrNote: 'ይህን አገናኝ በመጠቀም ማንኛውንም QR ኮድ ማመንጫ ድረ-ገጽ በመጠቀም አካላዊ QR ኮድ ማመንጨት ይችላሉ።',
    printQRCodes: 'QR ኮዶች አትም',
    generateAndPrintQRCodes: 'ለሁሉም ጠረጴዛዎች QR ኮዶች ፍጠር እና አትም',
    printAll: 'ሁሉንም አትም',
    copyUrl: 'አገናኝ ቅዳ',
    qrPrintInstructions: 'ይህን ገጽ አትመው እያንዳንዱን QR ኮድ ይቁረጡ። በተዛማጅ ጠረጴዛዎች ላይ ያስቀምጡ።',
    cutAndPlaceOnTables: 'QR ኮዶችን ቆርጠው በተዛማጅ ጠረጴዛዎች ላይ ያስቀምጡ።',
    howQrWorks: 'QR ትዕዛዝ እንዴት እንደሚሰራ',
    step1: 'በጠረጴዛዎ ላይ QR ኮድ ይቃኙ',
    step2: 'ምናሌውን ያስሱ እና እቃዎችን ይጨምሩ',
    step3: 'ዝርዝሮችዎን ያስገቡ',
    step4: 'ትዕዛዝ ያስገቡ - አስተናጋጅ ያረጋግጣል',
    scanToOrder: 'ለማዘዝ ቃኝ',
    viewMenu: 'ምናሌ ይመልከቱ',
    urlCopied: 'አገናኝ ተቀድቷል',
    yourOrderIsReady: 'ትዕዛዝዎ ለማንሳት ዝግጁ ነው!',
    orderCompletedThankYou: 'ትዕዛዝ ተጠናቋል! እንደበላችሁ እናመሰግናለን!',

    // ---------- INVENTORY ----------
    inventoryManagement: 'የእቃ ዝርዝር አያያዝ',
    manageProductsAndIngredients: 'ምርቶችን እና ጥሬ እቃዎችን ያስተዳድሩ',
    ingredients: 'ጥሬ እቃዎች',
    products: 'ምርቶች',
    addIngredient: 'ጥሬ እቃ ጨምር',
    addProduct: 'ምርት ጨምር',
    stock: 'ክምችት',
    minStock: 'ዝቅተኛ ክምችት',
    unit: 'ክፍል',
    unitCost: 'የክፍል ዋጋ',
    category: 'ምድብ',
    supplier: 'አቅራቢ',
    lowStock: 'ዝቅተኛ ክምችት',
    outOfStock: 'ክምችት የለም',
    inStock: 'ክምችት አለ',
    adjustStock: 'ክምችት አስተካክል',
    currentStock: 'አሁን ያለው ክምችት',
    lowStockDescription: 'የሚከተሉት ጥሬ እቃዎች ከዝቅተኛ ክምችት በታች ናቸው:',
    left: 'ቀርቷል',
    min: 'ዝቅተኛ',
    moreItems: 'ተጨማሪ እቃዎች',
    noIngredientsFound: 'ምንም ጥሬ እቃዎች አልተገኙም',
    noProductsFound: 'ምንም ምርቶች አልተገኙም',
    ingredientsBelowMinStock: 'ጥሬ እቃዎች ከዝቅተኛ ክምችት በታች ናቸው',
    selectUnit: 'ክፍል ምረጥ',
    kilogram: 'ኪሎ ግራም (ኪግ)',
    gram: 'ግራም (ግ)',
    liter: 'ሊትር (ሊ)',
    milliliter: 'ሚሊ ሊትር (ሚሊ)',
    pieces: 'ቁርጥራጭ (ቁርጥ)',
    egVegetables: 'ለምሳሌ: አትክልት',
    stockValue: 'የክምችት ዋጋ',
    reorderLevel: 'እንደገና የማዘዝ ደረጃ',
    available: 'ክፍት',
    unavailable: 'አይገኝም',

    // ---------- WASTAGE ----------
    wastageTracking: 'የቆሻሻ ክትትል',
    trackIngredientWaste: 'ከመግረዝ፣ ከመበላሸት እና ከማብሰል ኪሳራ የሚመጣውን የንጥረ ነገር ብክነት ይከታተሉ',
    wastagePercentage: 'የብክነት መጠን (%)',
    cookingLoss: 'የማብሰል ኪሳራ (%)',
    yieldPercentage: 'የምርት መጠን (%)',
    expectedUsage: 'የሚጠበቀው አጠቃቀም',
    actualUsage: 'ትክክለኛው አጠቃቀም',
    wastageAmount: 'የብክነት መጠን',
    wastageCost: 'የብክነት ዋጋ',
    totalWastageCost: 'ጠቅላላ የብክነት ዋጋ',
    wastageReport: 'የብክነት ሪፖርት',
    wastageByIngredient: 'በንጥረ ነገር የተከፋፈለ ብክነት',
    dailyWastage: 'ዕለታዊ ብክነት',
    wastageDescription: 'ምግብ በሚዘጋጅበት ጊዜ ሁሉም ንጥረ ነገሮች 100% አይጠቀሙም። አንዳንዶቹ በመግረዝ፣ በመበላሸት፣ በማፍሰስ እና በማብሰል ትነት ይጠፋሉ።',
    wastageExample: 'ምሳሌ: 250g ሥጋ + 15% ብክነት = 287.5g ከክምችት ይቀንሳል',
    trimmingWaste: 'መግረዝ እና መበላሸት',
    cookingEvaporation: 'የማብሰል ትነት (እየቀነሰ)',
    batchCooking: 'የቡድን ማብሰል ብቃት',
    autoWastageLearning: 'ከታሪካዊ መረጃ ራስ-ሰር የብክነት ምክንያቶችን መማር',
    lowStockCritical: 'ከባድ - አሁን እንደገና ይዘዙ',
    wastageAlert: 'ከፍተኛ ብክነት ማስጠንቀቂያ',
    wastageReductionTip: 'ምክር: ብክነትን ለመቀነስ እስከ 5-15% ወጪን ለመቀነስ ይከታተሉ',
    ingredientCostBreakdown: 'የንጥረ ነገር ወጪ ክፍፍል',
    defaultWastage: 'ነባሪ ብክነት',
    defaultWastagePercentage: 'ነባሪ የብክነት መጠን %',
    defaultCookingLossPercentage: 'ነባሪ የማብሰል ኪሳራ %',
    wastageSettings: 'የብክነት ቅንብሮች',

    // ---------- EXPENSES ----------
    expenseTracking: 'የወጪ ክትትል',
    trackBusinessOperationalCosts: 'የንግድ ሥራ ወጪዎችን ይከታተሉ',
    addExpense: 'ወጪ ጨምር',
    expenses: 'ወጪዎች',
    expenseCategory: 'የወጪ ምድብ',
    rent: 'ኪራይ',
    utilities: 'መገልገያዎች',
    salaries: 'ደሞዝ',
    marketing: 'ግብይት',
    maintenance: 'ጥገና',
    supplies: 'አቅርቦቶች',
    transport: 'ትራንስፖርት',
    insurance: 'ኢንሹራንስ',
    taxes: 'ታክሶች',
    other: 'ሌላ',
    recordedBy: 'የተመዘገበው በ',
    expenseDate: 'የወጪ ቀን',
    thisMonth: 'በዚህ ወር',
    thisYear: 'በዚህ ዓመት',
    from: 'ከ',
    to: 'ወደ',
    totalExpenses: 'ጠቅላላ ወጪዎች',
    averageDaily: 'አማካይ ዕለታዊ',
    perDay: 'በቀን',
    categories: 'ምድቦች',
    differentExpenseTypes: 'የተለያዩ የወጪ ዓይነቶች',
    expenseByCategory: 'ወጪ በምድብ',
    transactions: 'ግብይቶች',
    searchExpenses: 'ወጪዎችን ፈልግ...',
    noExpensesFound: 'ምንም ወጪዎች አልተገኙም',
    editExpense: 'ወጪ አርትዕ',
    selectCategory: 'ምድብ ምረጥ',
    optionalDescription: 'አማራጭ መግለጫ...',
    monthlyExpenses: 'ወርሃዊ ወጪዎች',
    expenseTrend: 'የወጪ አዝማሚያ',

    // ---------- PROFIT REPORTS ----------
    profitReports: 'የትርፍ ሪፖርቶች',
    trackYourBusinessProfitability: 'የንግድዎን ትርፋማነት ይከታተሉ',
    totalRevenue: 'ጠቅላላ ገቢ',
    totalCost: 'ጠቅላላ ወጪ',
    totalProfit: 'ጠቅላላ ትርፍ',
    profitMargin: 'የትርፍ ህዳግ',
    dailyBreakdown: 'ዕለታዊ ክፍፍል',
    topProducts: 'ከፍተኛ ምርቶች',
    byProfitContribution: 'በትርፍ አስተዋጽዖ',
    sold: 'ተሽጧል',
    revenue: 'ገቢ',
    cost: 'ወጪ',
    profit: 'ትርፍ',
    margin: 'ህዳግ',
    averageOrder: 'አማካይ ትዕዛዝ',
    todayPerformance: "የዛሬ አፈጻጸም",
    revenueProfitTrend: 'የገቢ እና ትርፍ አዝማሚያ',
    hourlySalesTrend: 'የሰዓት ሽያጭ አዝማሚያ',
    hour: 'ሰዓት',
    product: 'ምርት',
    report: 'ሪፖርት',
    generated: 'ተፈጥሯል',
    exportFailed: 'ወደ ውጭ መላክ አልተቻለም',
    pdfExportError: 'PDF የወጪ ስህተት',
    exportExcel: 'Excel ላክ',
    exportPDF: 'PDF ላክ',
    noDataToExport: 'ለመላክ ምንም ውሂብ የለም',
    salesReports: 'የሽያጭ ሪፖርቶች',
    performanceByDay: 'አፈጻጸም በቀን',
    noSalesDataForPeriod: 'ለተመረጠው ጊዜ ምንም የሽያጭ ውሂብ የለም',
    grossProfit: 'ጠቅላላ ትርፍ',
    netProfit: 'የተጣራ ትርፍ',
    operatingExpenses: 'የሥራ ወጪዎች',

    // ---------- STAFF ----------
    staffManagement: 'የሰራተኞች አያያዝ',
    manageStaffAccountsAndPermissions: 'የሰራተኞች መለያዎችን እና ፈቃዶችን ያስተዳድሩ',
    addStaff: 'ሰራተኛ ጨምር',
    editStaff: 'ሰራተኛ አርትዕ',
    deleteStaff: 'ሰራተኛ ሰርዝ',
    fullName: 'ሙሉ ስም',
    joinDate: 'የተቀላቀሉበት ቀን',
    lastLogin: 'የመጨረሻ ግቤት',
    pendingApproval: 'ማጽደቅ በመጠባበቅ ላይ',
    active: 'ንቁ',
    inactive: 'ንቁ ያልሆነ',
    pendingApprovals: 'በመጠባበቅ ላይ ያሉ ማጽደቆች',
    reviewAndApproveStaffAccounts: 'አዲስ የሰራተኞች መለያ ጥያቄዎችን ይገምግሙ እና ያጽድቁ',
    defaultRole: 'ነባር ሚና',
    userApproved: 'ተጠቃሚ በተሳካ ሁኔታ ጸድቋል',
    userRejected: 'ተጠቃሚ ውድቅ ተደርጓል',
    waitingForApproval: 'የአስተዳዳሪ ማጽደቅ በመጠባበቅ ላይ',
    staffPerformance: 'የሰራተኞች አፈጻጸም',
    salesPerformance: 'የሽያጭ አፈጻጸም',
    moreStaff: 'ተጨማሪ ሰራተኞች',
    noSalesData: 'ለዚህ ጊዜ ምንም የሽያጭ ውሂብ የለም',
    topPerformer: '🏆 ከፍተኛ አፈጻጸም',
    noStaffMembersFound: 'ምንም ሰራተኞች አልተገኙም',
    accessDeniedOnlyOwners: 'መድረስ አልተፈቀደም። ባለቤቶች እና አስተዳዳሪዎች ብቻ ሰራተኞችን ማየት ይችላሉ።',
    failedToLoadStaff: 'ሰራተኞችን መጫን አልተቻለም',
    staffUpdatedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ዘምኗል!',
    staffCreatedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ተፈጥሯል!',
    failedToSaveStaff: 'ሰራተኛውን ማስቀመጥ አልተቻለም',
    deleteStaffConfirm: 'ይህን ሰራተኛ መሰረዝ እርግጠኛ ነዎት?',
    staffDeletedSuccessfully: 'ሰራተኛ በተሳካ ሁኔታ ተሰርዟል!',
    failedToDeleteStaff: 'ሰራተኛውን መሰረዝ አልተቻለም',
    roles: 'ሚናዎች',
    clickAddStaffToCreate: 'አዲስ መለያ ለመፍጠር "ሰራተኛ ጨምር" ን ጠቅ ያድርጉ',
    editStaffMember: 'ሰራተኛ አርትዕ',
    addNewStaffMember: 'አዲስ ሰራተኛ ጨምር',
    enterFullName: 'ሙሉ ስም ያስገቡ',
    enterEmailAddress: 'ኢሜይል አድራሻ ያስገቡ',
    minimum6Characters: 'ቢያንስ 6 ቁምፊዎች',
    fullAccess: 'ሙሉ መዳረሻ',
    operationalAccess: 'የሥራ መዳረሻ',
    paymentOnly: 'ክፍያ ብቻ',
    orderTaking: 'ትዕዛዝ መውሰድ',
    foodPrepOnly: 'ምግብ ዝግጅት ብቻ',
    phoneNumber: 'ስልክ ቁጥር',
    optional: 'አማራጭ',
    updateStaff: 'ሰራተኛ አዘምን',
    createStaff: 'ሰራተኛ ፍጠር',
    accessDeniedOnlyOwnersAndAdmins: 'መድረስ አልተፈቀደም። በመጠባበቅ ላይ ያሉ ማጽደቆችን ማየት የሚችሉት ባለቤቶች እና አስተዳዳሪዎች ብቻ ናቸው።',
    failedToLoadPendingUsers: 'በመጠባበቅ ላይ ያሉ ተጠቃሚዎችን መጫን አልተቻለም',
    userApprovedSuccessfully: 'ተጠቃሚ በተሳካ ሁኔታ ጸድቋል! አሁን መግባት ይችላሉ።',
    failedToApproveUser: 'ተጠቃሚውን ማጽደቅ አልተቻለም',
    rejectUserConfirm: 'ይህን ተጠቃሚ ውድቅ ማድረግ እርግጠኛ ነዎት?',
    userRejectedAndRemoved: 'ተጠቃሚ ውድቅ ተደርጎ ተወግዷል።',
    failedToRejectUser: 'ተጠቃሚውን ውድቅ ማድረግ አልተቻለም',
    usersWaiting: 'ተጠቃሚዎች በመጠባበቅ ላይ',
    allStaffAccountsApproved: 'ሁሉም የሰራተኞች መለያዎች ጸድቀዋል',
    newStaffWillAppearHere: 'አዲስ ሰራተኞች ሲመዘገቡ እዚህ ይታያሉ',
    notProvided: 'አልቀረበም',
    requested: 'የተጠየቀ',
    assignRole: 'ሚና መድብ',
    basicAccess: 'መሰረታዊ መዳረሻ',
    operations: 'ስራዎች',
    tipApprovedUsersWillReceiveEmail: 'የጸደቁ ተጠቃሚዎች የኢሜይል ማሳወቂያ ይቀበላሉ',

    // ---------- RECIPES ----------
    recipeManagement: 'የምግብ አዘገጃጀት አያያዝ',
    defineProductRecipes: 'ለራስ-ሰር የክምችት ቅነሳ የምርት አዘገጃጀቶችን ይግለጹ',
    howRecipesWork: 'የምግብ አዘገጃጀት እንዴት እንደሚሰራ',
    recipeDescription: 'እያንዳንዱ ምርት ሁሉንም ንጥረ ነገሮች እና መጠኖች የሚዘረዝር የምግብ አዘገጃጀት ያስፈልገዋል።',
    setupRecipe: 'የምግብ አዘገጃጀት አዘጋጅ',
    viewRecipe: 'የምግብ አዘገጃጀት ይመልከቱ',
    calculateCost: 'ወጪ አስላ',
    ingredientsNeeded: 'የሚፈለጉ ንጥረ ነገሮች',
    totalIngredientCost: 'ጠቅላላ የንጥረ ነገር ወጪ',
    profitSummary: 'የትርፍ ማጠቃለያ',
    sellingPrice: 'የሽያጭ ዋጋ',
    ingredientCost: 'የንጥረ ነገር ዋጋ',
    recipeExists: 'የምግብ አዘገጃጀት ተዋቅሯል',
    noRecipe: 'ምንም የምግብ አዘገጃጀት አልተዋቀረም',
    failedToLoadRecipe: 'የምግብ አዘገጃጀት መጫን አልተቻለም',
    pleaseSelectIngredientAndQuantity: 'እባክዎ ንጥረ ነገር ይምረጡ እና መጠን ያስገቡ',
    pleaseAddAtLeastOneIngredient: 'እባክዎ ቢያንስ አንድ ንጥረ ነገር ይጨምሩ',
    recipeSavedSuccessfully: 'የምግብ አዘገጃጀት በተሳካ ሁኔታ ተቀምጧል!',
    failedToSaveRecipe: 'የምግብ አዘገጃጀት ማስቀመጥ አልተቻለም',
    noRecipeFoundForProduct: 'ለዚህ ምርት ምንም የምግብ አዘገጃጀት አልተገኘም',
    uncategorized: 'ያልተመደበ',
    recipe: 'የምግብ አዘገጃጀት',
    noIngredientsAddedYet: 'እስካሁን ምንም ንጥረ ነገሮች አልተጨመሩም',
    selectIngredient: 'ንጥረ ነገር ምረጥ',
    quantityRequired: 'የሚፈለገው መጠን',
    saveRecipe: 'የምግብ አዘገጃጀት አስቀምጥ',
    yieldQuantity: 'የምርት ብዛት',

    // ---------- CUSTOMERS ----------
    customerManagement: 'የደንበኞች አያያዝ',
    manageCustomerAccounts: 'የደንበኞች መለያዎችን እና ታማኝነትን ያስተዳድሩ',
    addCustomer: 'ደንበኛ ጨምር',
    editCustomer: 'ደንበኛ አርትዕ',
    deleteCustomer: 'ደንበኛ ሰርዝ',
    customerDetails: 'የደንበኛ ዝርዝሮች',
    totalCustomers: 'ጠቅላላ ደንበኞች',
    totalLoyaltyPoints: 'ጠቅላላ የታማኝነት ነጥቦች',
    totalSpent: 'ጠቅላላ ወጪ',
    avgSpentPerCustomer: 'አማካይ በእያንዳንዱ ደንበኛ',
    searchCustomers: 'ደንበኞችን ፈልግ...',
    noCustomersFound: 'ምንም ደንበኞች አልተገኙም',
    addYourFirstCustomer: 'የመጀመሪያ ደንበኛዎን ይጨምሩ',
    customerAddress: 'የደንበኛ አድራሻ',
    specialNotes: 'ልዩ ማስታወሻዎች',
    totalVisits: 'ጠቅላላ ጉብኝቶች',
    customerCreated: 'ደንበኛ በተሳካ ሁኔታ ተፈጥሯል',
    customerUpdated: 'ደንበኛ በተሳካ ሁኔታ ዘምኗል',
    customerDeleted: 'ደንበኛ በተሳካ ሁኔታ ተሰርዟል',
    deleteCustomerConfirm: 'ይህን ደንበኛ መሰረዝ እርግጠኛ ነዎት?',
    lastVisit: 'የመጨረሻ ጉብኝት',

    // ---------- SETTINGS ----------
    receiptFooter: 'የደረሰኝ ግርጌ መልእክት',
    restaurantName: 'የሬስቶራንት ስም',
    address: 'አድራሻ',
    workingHours: 'የስራ ሰዓታት',
    taxRate: 'የግብር መጠን',
    configureRestaurantPreferences: 'የሬስቶራንትዎን ምርጫዎች ያዋቅሩ',
    settingsSavedSuccessfully: 'ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል!',
    restaurantInformation: 'የሬስቶራንት መረጃ',
    businessSettings: 'የንግድ ቅንብሮች',
    receiptSettings: 'የደረሰኝ ቅንብሮች',
    thankYouForDining: 'እንደበላችሁ እናመሰግናለን!',
    saveSettings: 'ቅንብሮችን አስቀምጥ',
    settingsSaveInfo: 'ቅንብሮች በአሳሽዎ ውስጥ ተቀምጠዋል።',

    // ---------- NOTIFICATIONS ----------
    lowStockAlert: 'ዝቅተኛ ክምችት ማስጠንቀቂያ',
    newOrderAlert: 'አዲስ ትዕዛዝ ማስጠንቀቂያ',
    orderReadyAlert: 'ትዕዛዝ ዝግጁ ማስጠንቀቂያ',
    salesReportReady: 'የሽያጭ ሪፖርት ዝግጁ',
    markAllRead: 'ሁሉንም እንደተነበበ ምልክት አድርግ',
    noNotifications: 'ምንም ማሳወቂያዎች የሉም',
    orderStatusUpdated: 'የትዕዛዝ ሁኔታ ዘምኗል',
    tableStatusUpdated: 'የጠረጴዛ ሁኔታ ዘምኗል',

    // ---------- ORDER CANCELLATION ----------
    cancelOrderTitle: 'ትዕዛዝ ሰርዝ',
    voidOrderTitle: 'ትዕዛዝ ባዶ አድርግ',
    cancellationReasonPlaceholder: 'ይህ ትዕዛዝ የተሰረዘው ለምንድነው?',
    voidReasonPlaceholder: 'ይህ ትዕዛዝ ባዶ የሚደረገው ለምንድነው?',
    voidDescription: 'ባዶ ማድረግ ትዕዛዙን ከሽያጭ መዝገቦች ያስወግዳል እና ክምችትን ይመልሳል።',
    customerChangedMind: 'ደንበኛ ሀሳቡን ቀይሯል',
    customerLeft: 'ደንበኛ ሬስቶራንቱን ለቋል',
    orderTooLong: 'ትዕዛዝ ጊዜ ወስዷል',
    wrongItems: 'የተሳሳቱ እቃዎች ታዘዋል',
    duplicateOrder: 'የተደጋገመ ትዕዛዝ',
    paymentIssue: 'የክፍያ ችግር',
    kitchenCannotPrepare: 'ኩሽና ማዘጋጀት አይችልም',
    systemError: 'የሲስተም ስህተት - ድርብ ክፍያ',
    trainingError: 'የሰራተኛ ስልጠና ስህተት',
    testOrder: 'የሙከራ ትዕዛዝ',
    wrongTable: 'የተሳሳተ ጠረጴዛ ተከፍሏል',
    overcharged: 'ደንበኛ ከመጠን በላይ ተከፍሏል',
    cancellationReason: 'የስረዛ ምክንያት',
    yesCancel: 'አዎ፣ ሰርዝ',
    noKeep: 'አይ፣ አትሰርዝ',

    // ---------- DASHBOARD ----------
    businessPerformance: 'የንግድ አፈጻጸም አጠቃላይ እይታ',
    todayRevenue: "የዛሬ ገቢ",
    todayProfit: "የዛሬ ትርፍ",
    monthRevenue: 'የወር ገቢ',
    monthProfit: 'የወር ትርፍ',
    weeklyTrend: 'ሳምንታዊ አዝማሚያ',
    monthlyTrend: 'ወርሃዊ አዝማሚያ',
    yearlyTrend: 'አመታዊ አዝማሚያ',
    topSellingProducts: 'ከፍተኛ ሽያጭ ያላቸው ምርቶች',
    recentSales: 'የቅርብ ጊዜ ሽያጮች',
    paymentMethods: 'የክፍያ ዘዴዎች',
    hourlySales: 'የሰዓት ሽያጮች',
    dailyOrders: 'ዕለታዊ ትዕዛዞች',
    totalProducts: 'ጠቅላላ ምርቶች',
    needReorder: 'እንደገና ማዘዝ ያስፈልጋል',
    critical: 'ከባድ',
    latestTransactions: 'የቅርብ ጊዜ ግብይቶች',
    cashier: 'ገንዘብ ተቀባይ',
    system: 'ሲስተም',
    noSalesYet: 'እስካሁን ሽያጭ የለም',
    weekRevenue: 'የሳምንት ገቢ',
    gross: 'ጠቅላላ',
    netProfitMargin: 'የተጣራ ትርፍ ህዳግ',
    quickSummary: 'ፈጣን ማጠቃለያ',
    avgOrderValue: 'አማካይ የትዕዛዝ ዋጋ',
    ownerDashboard: 'የባለቤት ዳሽቦርድ',
    fullBusinessAnalytics: 'ሙሉ የንግድ ትንታኔ እና ቁጥጥር',
    totalStaff: 'ጠቅላላ ሰራተኞች',
    activeEmployees: 'ንቁ ሰራተኞች',
    totalOrders: 'ጠቅላላ ትዕዛዞች',
    monthNetProfit: 'የወር የተጣራ ትርፍ',

    // ---------- MANAGER ----------
    managerDashboard: 'የአስተዳዳሪ ዳሽቦርድ',
    operationalOverview: 'የሥራ አጠቃላይ እይታ',
    todaySales: "የዛሬ ሽያጭ",
    staffOnDuty: 'በስራ ላይ ያሉ ሰራተኞች',
    ingredientsNeedReorder: 'ንጥረ ነገሮች እንደገና ማዘዝ ያስፈልጋል',
    updateInventory: 'ክምችት አዘምን',
    addOrEditStockLevels: 'የክምችት ደረጃዎችን ይጨምሩ ወይም ያርትዑ',
    viewReports: 'ሪፖርቶችን ይመልከቱ',
    salesAndProfitAnalytics: 'የሽያጭ እና ትርፍ ትንታኔ',

    // ---------- AUTH ----------
    restaurantManagementSystem: 'የሬስቶራንት አያያዝ ሲስተም',
    emailAddress: 'ኢሜይል አድራሻ',
    loggingIn: 'በመግባት ላይ...',
    signIn: 'ግባ',
    noAccount: 'መለያ የለዎትም?',
    signUp: 'ተመዝገብ',
    demoAccounts: 'የማሳያ መለያዎች',
    createAccount: 'መለያዎን ይፍጠሩ',
    fullNamePlaceholder: 'ሙሉ ስም',
    passwordMinLengthPlaceholder: 'ቢያንስ 6 ቁምፊዎች',
    passwordMinLengthHint: 'ቢያንስ 6 ቁምፊዎች',
    creatingAccount: 'መለያ በመፍጠር ላይ...',
    alreadyHaveAccount: 'አስቀድመው መለያ አለዎት?',
    accountCreated: 'መለያ ተፈጥሯል!',
    accountPendingApproval: 'መለያዎ ተፈጥሯል እና የአስተዳዳሪ ማጽደቅ በመጠባበቅ ላይ ነው።',
    goToLogin: 'ወደ መግቢያ ሂድ',
    signupFailed: 'ምዝገባ አልተሳካም',
    emailPasswordRequired: 'ኢሜይል እና የይለፍ ቃል ያስፈልጋሉ',
    loginFailed: 'መግባት አልተሳካም',
    invalidCredentials: 'የተሳሳተ ኢሜይል ወይም የይለፍ ቃል',
    accountPending: 'መለያ በመጠባበቅ ላይ ነው። እባክዎ ይጠብቁ።',
    accountDeactivated: 'መለያ ተቋርጧል። አስተዳዳሪ ያግኙ።',
    networkError: 'የአውታረ መረብ ስህተት። እባክዎ ግንኙነትዎን ያረጋግጡ።',
    saveSuccess: 'በተሳካ ሁኔታ ተቀምጧል',
    requiredField: 'ይህ መስክ ያስፈልጋል',
    passwordMinLength: 'የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    emailInvalid: 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
    stockInsufficient: 'በቂ ክምችት የለም',
    invalidEmailOrPassword: 'የተሳሳተ ኢሜይል ወይም የይለፍ ቃል',

    // ---------- TIME PERIODS ----------
    last7Days: 'ያለፉት 7 ቀናት',
    last30Days: 'ያለፉት 30 ቀናት',
    last365Days: 'ያለፉት 365 ቀናት',
    week: 'ሳምንት',
    month: 'ወር',
    year: 'ዓመት',
    today: 'ዛሬ',
    yesterday: 'ትላንት',
    tomorrow: 'ነገ',

    // ---------- WEEK DAYS ----------
    monday: 'ሰኞ',
    tuesday: 'ማክሰኞ',
    wednesday: 'ረቡዕ',
    thursday: 'ሐሙስ',
    friday: 'ዓርብ',
    saturday: 'ቅዳሜ',
    sunday: 'እሑድ',

    // ---------- MONTHS ----------
    january: 'ጥር',
    february: 'የካቲት',
    march: 'መጋቢት',
    april: 'ሚያዝያ',
    may: 'ግንቦት',
    june: 'ሰኔ',
    july: 'ሐምሌ',
    august: 'ነሐሴ',
    september: 'መስከረም',
    october: 'ጥቅምት',
    november: 'ህዳር',
    december: 'ታህሳስ',

    // ---------- SALES ----------
    sales: 'ሽያጮች',
    avgOrder: 'አማካይ ትዕዛዝ',
    only: 'ብቻ',
    customers: 'ደንበኞች',

    // ---------- ASSIGN WAITERS ----------
    assignWaitersToTables: 'አስተናጋጆችን ለጠረጴዛዎች መድብ',
    assignWaitersDescription: 'አስተናጋጆችን የተወሰኑ ጠረጴዛዎችን እንዲያስተዳድሩ መድብ',
    assignWaitersInfo: 'አስተናጋጆች በተመደቡላቸው ጠረጴዛዎች ላይ ለሚመጡ ትዕዛዞች ማሳወቂያ ይቀበላሉ',
    availableWaiters: 'ክፍት አስተናጋጆች',
    assignedTables: 'የተመደቡ ጠረጴዛዎች',
    currentStatus: 'አሁን ያለው ሁኔታ',
    assignedWaiter: 'የተመደበ አስተናጋጅ',
    selectWaiter: 'አስተናጋጅ ምረጥ',
    waiterAssigned: 'አስተናጋጅ ተመድቧል',
    noWaitersAvailable: 'ምንም ክፍት አስተናጋጆች የሉም',
    addWaitersFirst: 'እባክዎ መጀመሪያ አስተናጋጆችን ያክሉ',
    failedToLoadData: 'ውሂብ መጫን አልተቻለም',
    waiterAssignedSuccessfully: 'አስተናጋጅ በተሳካ ሁኔታ ተመድቧል',
    failedToAssignWaiter: 'አስተናጋጅ መመደብ አልተቻለም',

    // ---------- MANAGE TABLES ----------
    addEditRemoveTables: 'የሬስቶራንት ጠረጴዛዎችን ያክሉ፣ ያርትዑ ወይም ያስወግዱ',
    addTable: 'ጠረጴዛ ጨምር',
    editTable: 'ጠረጴዛ አርትዕ',
    totalTables: 'ጠቅላላ ጠረጴዛዎች',
    reservedCleaning: 'የተያዘ / እየተጸዳ',
    addNewTable: 'አዲስ ጠረጴዛ ጨምር',
    tableNumber: 'የጠረጴዛ ቁጥር',
    initialStatus: 'የመጀመሪያ ሁኔታ',
    newTableNote: 'አዳዲስ ጠረጴዛዎች ለመቀመጫ ዝግጁ ይሆናሉ',
    failedToSaveTable: 'ጠረጴዛ ማስቀመጥ አልተቻለም',
    deleteTableConfirm: 'ይህን ጠረጴዛ መሰረዝ እርግጠኛ ነዎት?',
    failedToDeleteTable: 'ጠረጴዛ መሰረዝ አልተቻለም',
    updatedSuccessfully: 'በተሳካ ሁኔታ ተዘምኗል',
    createdSuccessfully: 'በተሳካ ሁኔታ ተፈጥሯል',
    deletedSuccessfully: 'በተሳካ ሁኔታ ተሰርዟል',
    qrUrlCopied: 'QR አገናኝ ተቀድቷል',

    // ---------- PRODUCTS ----------
    productUpdatedSuccessfully: 'ምርት በተሳካ ሁኔታ ዘምኗል!',
    productCreatedSuccessfully: 'ምርት በተሳካ ሁኔታ ተፈጥሯል!',
    productDeletedSuccessfully: 'ምርት በተሳካ ሁኔታ ተሰርዟል',


    // ============================================
// SIDEBAR MENU ITEMS (AMHARIC)
// ============================================
tableManagement: 'የጠረጴዛ አያያዝ',
myOrders: 'የኔ ትዕዛዞች',
confirmOrders: 'ትዕዛዞችን አረጋግጥ',
posTerminal: 'የሽያጭ መዝገብ',
manualOrder: 'በእጅ ትዕዛዝ',
tableStatus: 'የጠረጴዛ ሁኔታ',
kitchenOrders: 'ትዕዛዞች',

// ============================================
// CASHIER PAGE (AMHARIC)
// ============================================
readyForPayment: 'ለክፍያ ዝግጁ',
salesHistory: 'የሽያጭ ታሪክ',

// ============================================
// KITCHEN BUTTONS (AMHARIC)
// ============================================
startCooking: 'ማብሰል ጀምር',
markReady: 'ዝግጁ ምልክት አድርግ',
readyForPickup: 'ለማንሳት ዝግጁ',
noOrdersToDisplay: 'ለማሳየት ምንም ትዕዛዞች የሉም',
ordersWillAppearHere: 'ትዕዛዞች ሲፈጠሩ እዚህ ይታያሉ',
pending: 'በመጠባበቅ ላይ',
preparing: 'በዝግጅት ላይ',
ready: 'ዝግጁ',
active: 'ንቁ',
order: 'ትዕዛዝ',
items: 'እቃዎች',
more: 'ተጨማሪ',
customer: 'ደንበኛ',
table: 'ጠረጴዛ',
waitingTime: 'የጥበቃ ጊዜ',
kitchenStatus: 'የኩሽና ሁኔታ',
failedToUpdateOrderStatus: 'የትዕዛዝ ሁኔታ ማዘመን አልተቻለም',
newOrderReceived: 'አዲስ ትዕዛዝ ደርሷል',
orderSent: 'ትዕዛዝ ወደ ኩሽና ተልኳል',
  },
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'am' ? 'am' : 'en';
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};